### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by kerberjg** [snowballdigital/flutter-unity-view-widget#1]
Hello, is iOS support planned?
I would love to help with testing if necessary, once there's an example available

**Comment by juicycleff** [comment]
Sure @kerberjg iOS support will be ready later tomorrow. And then docs on Saturday

**Comment by armandsLa** [comment]
Any updates on iOS support?

**Comment by juicycleff** [comment]
Sorry guys a bit delay on my end. Moved to Norway over the weekend my flight was moved over the weekend, which affected the timeline. But should be up this week. Hang in guys

**Comment by ataylor09** [comment]
This project looks promising, any update on iOS support?

**Comment by jarrodsinclair** [comment]
Hi, following the steps and testing with iOS gives the following error:

```
> flutter run
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            1.7s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/jarrod/Tools/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.3+3/ios/Classes/FlutterUnityWidgetPlugin.m:2:9: fatal error: 'flutter_unity_widget/flutter_unity_widget-Swift.h' file not found
    #import <flutter_unity_widget/flutter_unity_widget-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.
```

I don't see any ```flutter_unity_widget-Swift.h``` file in the repository, is this file generated?

**Comment by juicycleff** [comment]
@jarrodsinclair that's an error in the commit. I need some help adding working on iOS due to time. But I will try to finish support for it. I hope my new machine arrives today with bigger storage as my current MAC is completely filled up

**Comment by anilmaddala** [comment]
@juicycleff Thanks for the great work. I am able to run the plugin for Android but not iOS. I am looking forward for this fix. Is there any update?

**Comment by Warhammer4000** [comment]
@juicycleff is there any update coming soon on iOS?

**Comment by qiuguian** [comment]
the issue is not fix yet!?
