### ISSUE TITLE
Multiple Unity Game inside Flutter

### ISSUE THREAD

**Issue by rahul-sinha1908** [snowballdigital/flutter-unity-view-widget#100]
Hi  
I was working on a flutter project in which I needed to integrate multiple Unity mini-games. I see that your example shows in a very good way how we can integrate a single game to the flutter application.  
Is there a way, we can integrate multiple unity projects in the same flutter application through this dependency.  
Thanks in advance :)

**Comment by leemuljadi** [comment]
Possibly duplication of https://github.com/snowballdigital/flutter-unity-view-widget/issues/96
