### ISSUE TITLE
Execution failed for task ':app:mergeDebugNativeLibs'.

### ISSUE THREAD

**Issue by matwright** [snowballdigital/flutter-unity-view-widget#102]
Hi, I've installed the comonent today. Great job! However, I'm having a problem with the build in Android Studio. I was wondering if anyone has had the same issue. I'm using an ARCore Unity project. So, as per the predictions in the docs, some of the lib .so files were not exported across from Unity. I followed the docs instructions and unzipped an APK to manually copy them across. Now I have the following build error(s):

Execution failed for task ':app:mergeDebugNativeLibs'.

    A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
    More than one file was found with OS independent path 'lib/armeabi-v7a/libarcore_sdk_jni.so'

Any thoughts?

**Comment by juicycleff** [comment]
@matwright look at the ARKit example repo at the top description

**Comment by juicycleff** [comment]
If you still have issues, you can reopen
