### ISSUE TITLE
Failed to build apk using flutter 1.12 stable version

### ISSUE THREAD

**Issue by syah769** [snowballdigital/flutter-unity-view-widget#104]
Using 1.12 flutter version only work in debug mode. It's failed when I tried to build apk . I have to downgrade 1.9 stable version

Anyone has a problem like this and how to solve it? I think it's not a problem on unity plugin

**Comment by subjectdenied** [comment]
by "fail" you mean it crashes on launch, or even doesn't compile? if you mean crash, add --no-shrink to the flutter build command

**Comment by syah769** [comment]
> by "fail" you mean it crashes on launch, or even doesn't compile? if you mean crash, add --no-shrink to the flutter build command

doesn't compile . So far, it's not crashes .

**Comment by rafbanaan** [comment]
Which error do you receive?

**Comment by juicycleff** [comment]
@syah769 the example was updated and supports tested on latest flutter version
