### ISSUE TITLE
Issue when when the flutter_unity_widget is destroyed.

### ISSUE THREAD

**Issue by rahul-sinha1908** [snowballdigital/flutter-unity-view-widget#105]
I am getting an error when I try to navigate from one page(that contains flutter_unity_widget) to another page. The issues is popping up whenever the UnityWidget is getting destroyed. Looks I missed installing some plugin that handles the dispose function of flutter_unity_widget.   
  
Due to this error, I am not able to restart the UnityWidget, when I switch back to the previous scene and the app crashes.   
  
I am attaching the logs I am getting.  
Looking forward :)  

`
E/flutter (15485): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel unity_view_0)
E/flutter (15485): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter (15485): <asynchronous suspension>
E/flutter (15485): #1      UnityWidgetController._dispose 
package:flutter_unity_widget/flutter_unity_widget.dart:55
E/flutter (15485): #2      _UnityWidgetState.dispose 
package:flutter_unity_widget/flutter_unity_widget.dart:103
E/flutter (15485): #3      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4435
E/flutter (15485): #4      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1748
E/flutter (15485): #5      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #6      ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #7      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #8      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #9      MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5534
E/flutter (15485): #10     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #11     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #12     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #13     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #14     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #15     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (15485): #16     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #17     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #18     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #19     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #20     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #21     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #22     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #23     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #24     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (15485): #25     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #26     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #27     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #28     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #29     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #30     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (15485): #31     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #32     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #33     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5433
E/flutter (15485): #34     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #35     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1746
E/flutter (15485): #36     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4272
E/flutter (15485): #37     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1744
E/flutter (15485): #38     _InactiveElements._unmount.<anonymous closure> 
E/flutter (15485): #39     SingleChildRenderObjectElement.visitChildren (package:flutter/src/w
E/flutter (15485): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for void com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator() (tried Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator and Java_com_unity3d_player_UnityPlayer_nativeRestartActivityIndicator__)
E/flutter (15485): 	at com.unity3d.player.UnityPlayer.nativeRestartActivityIndicator(Native Method)
E/flutter (15485): 	at com.unity3d.player.UnityPlayer.resume(Unknown Source:23)
E/flutter (15485): 	at com.rexraphael.flutterunitywidget.UnityUtils.addUnityViewToGroup(UnityUtils.java:141)
E/flutter (15485): 	at com.rexraphael.flutterunitywidget.UnityView.setUnityPlayer(UnityView.java:21)
E/flutter (15485): 	at com.rexraphael.flutterunitywidget.FlutterUnityView.getUnityView(FlutterUnityView.java:101)
E/flutter (15485): 	at com.rexraphael.flutterunitywidget.FlutterUnityView.<init>(FlutterUnityView.java:30)
E/flutter (15485): 	at com.rexraphael.flutterunitywidget.FlutterUnityViewFactory.create(FlutterUnityViewFactory.java:34)
E/flutter (15485): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:174)
E/flutter (15485): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
E/flutter (15485): 	at android.app.Dialog.show(Dialog.java:302)
E/flutter (15485): 	at android.app.Presentation.show(Presentation.java:249)
E/flutter (15485): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/flutter (15485): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:53)
E/flutter (15485): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:105)
E/flutter (15485): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (15485): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (15485): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (15485): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (15485): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (15485): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (15485): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/flutter (15485): 	at android.os.Looper.loop(Looper.java:142)
E/flutter (15485): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
E/flutter (15485): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (15485): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/flutter (15485): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
E/flutter (15485):
F/flutter (15485): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
`

**Comment by kingkimohero69** [comment]
I think your issue is related to this #46

**Comment by rahul-sinha1908** [comment]
Thanks that solved the issue.

**Comment by Jairolaya12x** [comment]
Hey @rahul-sinha1908 how solve the problem?, I want restart the scene when back to other screen, any solution? thanks.

**Comment by folcjin** [comment]
https://folcjin.tistory.com/116

**Comment by NileshTech** [comment]
Call navigation first and then call 
await _unityWidgetController.unload();

I solved this blocker by this way
