### ISSUE TITLE
'UnityUtils.h' file not found

### ISSUE THREAD

**Issue by rafbanaan** [snowballdigital/flutter-unity-view-widget#106]
I'm trying to build my project for iOS. I followed the steps from the readme, but I receive the following error when building it: `'UnityUtils.h' file not found`.

I compared my files with the example, but I can't see any differents.

**Comment by kingkimohero69** [comment]
I faced this problem too , try to follow subjectdenied steps , i think it will work #93

**Comment by rafbanaan** [comment]
Nope, didn't do anything.

**Comment by kingkimohero69** [comment]
Sorry for late reply ,i really faced it when following the issue i mentioned before, i think you made a mistake you did not intend to do, i will try to give you some other related steps i did to make it working:
1- make sure to select unity scene in build settings and check arkit support in player settings then export in flutter
2-when adding unityexport project to pods select only flutter target.
3-follow subjectdenied steps no more or less as i did make some other unwanted steps and it caused me some errors like yours
If you did not manage to make it work i can provide you with some pics.
I used catalinaOS , iphone 7 with ios 13.3, xcode11.3

**Comment by khalithartmann** [comment]
@kingkimohero69  what did you mean with the 2. step
