### ISSUE TITLE
The dispose don't works in iOS

### ISSUE THREAD

**Issue by Jairolaya12x** [snowballdigital/flutter-unity-view-widget#107]
Hi, we have a problem with the dispose method.

Every time that back to the previous page get at error and the widget don't remove the state, and if want change some data preserve the old callbacks, 

For example the first time that user the unity widget add a listener for get the data from unity, and post a message when the data from unity is done, and works well, but the second time that try to make the same with other data (other product) keep sending the first data, and keep the first model in unity, a quick fix was force the load scene, but the callbacks don't see a way to get this, any idea?

This is the error in the dispose call:
`2020-02-21 17:57:23.418532-0500 Runner[892:270846] flutter: call the dispose of the unity
2020-02-21 17:57:23.438299-0500 Runner[892:270846] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel unity_view_0)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1 UnityWidgetController._dispose`

Thanks

**Comment by rod5438** [comment]
I got the similar issue. When I need to dispose UnityWidget, app crash.
Flutter version 1.14.6
Pixel 3

**Comment by juicycleff** [comment]
@rod5438 @Jairolaya12x I'm looking inti this

**Comment by juicycleff** [comment]
@rod5438 this issue has been fixed. Please look at the example, its updated

**Comment by benjwilson10** [comment]
Hi, after checking the FlutterUnityWidgetPlugin.m, the only method call that is handled is postMessage. So the dispose call is defaulting to: FlutterMethodNotImplemented. Is it possible to dispose of the UnityAppController properly?

Thanks

**Comment by guoguoguilai** [comment]
> I got the similar issue. When I need to dispose UnityWidget, app crash.
> Flutter version 1.14.6
> Pixel 3

The same issue. Did you find any solution for Android?

**Comment by Darkmax** [comment]
I also have this issue in android, this is not officially resolved. There's a workaround that is managing this by messages, but is not ideal for all applications.

**Comment by Darkmax** [comment]
> Hi, we have a problem with the dispose method.
> 
> Every time that back to the previous page get at error and the widget don't remove the state, and if want change some data preserve the old callbacks,
> 
> For example the first time that user the unity widget add a listener for get the data from unity, and post a message when the data from unity is done, and works well, but the second time that try to make the same with other data (other product) keep sending the first data, and keep the first model in unity, a quick fix was force the load scene, but the callbacks don't see a way to get this, any idea?
> 
> This is the error in the dispose call:
> `2020-02-21 17:57:23.418532-0500 Runner[892:270846] flutter: call the dispose of the unity 2020-02-21 17:57:23.438299-0500 Runner[892:270846] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel unity_view_0) #0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7) <asynchronous suspension> #1 UnityWidgetController._dispose`
> 
> Thanks

Did you resolve your problem @Jairolaya12x, because I'm facing the same problem on ios
