### ISSUE TITLE
Flutter run fail but xcode can work 

### ISSUE THREAD

**Issue by skypu3** [snowballdigital/flutter-unity-view-widget#108]
Hi All,
My flutter version is 1.12, and I try to run the command "flutter run", but it output following error
    /Users/felixchang/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+5/ios/Classes/FlutterUnityWidgetP
    lugin.m:12:10: fatal error: 'UnityFramework/UnityFramework.h' file not found
    #include <UnityFramework/UnityFramework.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    8 warnings and 1 error generated.

However, it works on xcode (open xcode and xcworkspace), does everyone know about the issues?

**Comment by skypu3** [comment]
BTW, I used the ar foundation sample

**Comment by qargali** [comment]
> Hi All,
> My flutter version is 1.12, and I try to run the command "flutter run", but it output following error
> /Users/felixchang/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+5/ios/Classes/FlutterUnityWidgetP
> lugin.m:12:10: fatal error: 'UnityFramework/UnityFramework.h' file not found
> #include <UnityFramework/UnityFramework.h>
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 8 warnings and 1 error generated.
> 
> However, it works on xcode (open xcode and xcworkspace), does everyone know about the issues?

Hello have you been able to solve this issue? if so could you share the solution to it?

**Comment by khalithartmann** [comment]
did anyone solve this issue?
