### ISSUE TITLE
The Example Doesnt Work, Whats wrong? New Version of Flutter not supported?

### ISSUE THREAD

**Issue by 5lineofcode** [snowballdigital/flutter-unity-view-widget#109]
launching lib/main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :UnityExport.
     Required by:
         project :app > project :flutter_unity_widget
      > Unable to find a matching configuration of project :UnityExport: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 52s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

##########

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.153, on Mac OS X 10.14.5 18F2059, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

• No issues found!
PTs-MacBook-Air:example sofco$ 

####

Flutter 1.15.4-pre.153 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9b3754d56f (2 days ago) • 2020-02-24 16:42:30 -0800
Engine • revision f2f8c342be
Tools • Dart 2.8.0 (build 2.8.0-dev.9.0 0f141be8bd)

**Comment by juicycleff** [comment]
@5lineofcode this has been fixed in the example and package itself
