### ISSUE TITLE
implementing Vuforia AR

### ISSUE THREAD

**Issue by wawa2016** [snowballdigital/flutter-unity-view-widget#11]
The example file works for me however when I also tried to do that with Vuforia AR which in UnityExport generates a new file 'VuforiaWrapper.aar' that I also dropped into unity-classes.

It gives me an error: 

Could not determine the dependencies of task ':flutter_unity_widget:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':flutter_unity_widget:debugRuntimeClasspath'.
   > Could not find :VuforiaWrapper:.
     Required by:
         project :flutter_unity_widget > project :UnityExport

Could you please help me to implement it?

**Comment by ajanieniolasolomon** [comment]
https://developer.vuforia.com/forum/unity/vuforia-wrapper-error-unity-module-inside-android-studio-project

**Comment by juicycleff** [comment]
@wawa2016 @lorant-csonka-planorama updated the instruction, you should try looking at it

**Comment by juicycleff** [comment]
@wawa2016 @thomas-stockx created a
