### ISSUE TITLE
package com.unity3d.* does not exist

### ISSUE THREAD

**Issue by jacknaish** [snowballdigital/flutter-unity-view-widget#110]
Hello, I am following the setup instructions within the readme. When I try to build the app I get the following error:

`
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityView.java:9: error: pack
age com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityView.java:13: error: can
not find symbol
    private UnityPlayer view;
            ^
  symbol:   class UnityPlayer
  location: class UnityView
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityView.java:19: error: can
not find symbol
    public void setUnityPlayer(UnityPlayer player) {
                               ^
  symbol:   class UnityPlayer
  location: class UnityView
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityUtils.java:10: error: pa
ckage com.unity3d.player does not exist
import com.unity3d.player.UnityPlayer;
                         ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityUtils.java:23: error: ca
nnot find symbol
    private static UnityPlayer unityPlayer;
                   ^
  symbol:   class UnityPlayer
  location: class UnityUtils
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityUtils.java:30: error: ca
nnot find symbol
    public static UnityPlayer getPlayer() {
                  ^
  symbol:   class UnityPlayer
  location: class UnityUtils
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityUtils.java:55: error: ca
nnot find symbol
                unityPlayer = new UnityPlayer(isAR ? activity : activity.getApplicationContext());
                                  ^
  symbol: class UnityPlayer
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\UnityUtils.java:79: error: ca
nnot find symbol
        UnityPlayer.UnitySendMessage(gameObject, methodName, message);
        ^
  symbol:   variable UnityPlayer
  location: class UnityUtils
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_unity_widget-0.1.6+5\android\src\main\java\com\rexraphael\flutterunitywidget\FlutterUnityViewFactory
.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
8 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_unity_widget:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         4.9s
Gradle task assembleDebug failed with exit code 1
`

**Comment by kingk5** [comment]
same error here anyone solved it yet
