### ISSUE TITLE
add unity-classes.jar from VSCode

### ISSUE THREAD

**Issue by MarijnFK** [snowballdigital/flutter-unity-view-widget#111]
I'm trying to follow the steps to get everything setup.
In step 1 you write:

> After exporting the unity game, open Android Studio and and add the Unity Classes Java .jar file as a module to the unity project. You just need to do this once if you are exporting from the same version of Unity everytime. The .jar file is located in the <Your Flutter Project>/android/UnityExport/lib folder

I'm not sure what you mean. I've watched the video (https://www.youtube.com/watch?v=exNPmv_7--Q) but he uses Android Studio -> Add as Library. I don't have that option in VSCode.

**Comment by Darkness4** [comment]
You have to do it manually.

First, you need to create a folder named `unity-classes` in the following path `./android/unity-classes`.
In this directory, you will need to add the `unity-classes.jar` file and create a build.gradle containing : 

```gradle
configurations.maybeCreate("default")
artifacts.add("default", file('unity-classes.jar'))
 ```

Then you will need to modify the first line of `./android/settings.gradle` : 

```gradle
include ':app'
```

to : 

```gradle
include ':app', ':unity-classes'
```

If there other files in libs such as  `UnityARCore.aar`, you should do the same steps and edit `./android/UnityExport/build.gradle` and replace `implementation(name: 'UnityARCore', ext:'aar')` with `implementation project(':UnityARCore')`.
