### ISSUE TITLE
Android - Add Unity Build Scripts and Export

### ISSUE THREAD

**Issue by Syzhra** [snowballdigital/flutter-unity-view-widget#112]
Following the README I could not finish the setup, and using the video and the example project I could complete.

To complete I did the following:

So I created the folder **unity-classes** and inside and put my **unity-classes.jar** file generated in the Unity Export step and this other file [build.gradle](https://github.com/snowballdigital/flutter-unity-view-widget/blob/master/example/android/unity-classes/build.gradle)

**Comment by Darkness4** [comment]
You will need to modify the first line of `./android/settings.gradle` : 

```gradle
include ':app'
```

to : 

```gradle
include ':app', ':unity-classes'
```
