### ISSUE TITLE
Can't build release

### ISSUE THREAD

**Issue by phamtuongvan** [snowballdigital/flutter-unity-view-widget#114]
When i build debug it work well. But if i build release it show error.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':flutter_unity_widget:profileRuntimeClasspath'.
   > Could not resolve project :UnityExport.
     Required by:
         project :flutter_unity_widget
      > Unable to find a matching variant of project :UnityExport:
          - Variant 'debugApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'debugRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'debug'.
              - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.
          - Variant 'releaseApiElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found incompatible value 'java-api'.
          - Variant 'releaseRuntimeElements':
              - Required com.android.build.api.attributes.BuildTypeAttr 'profile' and found incompatible value 'release'.
              - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
              - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
              - Required org.gradle.usage 'java-runtime' and found compatible value 'java-runtime'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Finished with error: Gradle task assembleRelease failed with exit code 1

**Comment by TarekMedhat** [comment]
In UnityExport/build.gradle
Add 
```
android {
  buildTypes {
      profile {}
    }
....
}
```
