### ISSUE TITLE
java.lang.NoSuchMethodError: no non-static method with name='onUnityMessage' signature='(Ljava/lang/String;)V' in class Lcom.rexraphael.flutterunitywidget.UnityUtils;

### ISSUE THREAD

**Issue by 0015** [snowballdigital/flutter-unity-view-widget#119]
Unity version 2019.3.7f1 
flutter_unity_widget: ^0.1.6+8

I'm trying the example for Android build.
onUnityMessage is not called when touching the cube in the Unity Screen. It says "java.lang.NoSuchMethodError: no non-static method with name='onUnityMessage' signature='(Ljava/lang/String;)V' in class Lcom.rexraphael.flutterunitywidget.UnityUtils;" 

Do I set the Custom Proguard to fix this issue?

**Comment by juicycleff** [comment]
Yes I believe so, because that method exists

**Comment by guoguoguilai** [comment]
Same issue. How to  solve this problem?
