### ISSUE TITLE
unity_2019_3_5_later/UnityMessageManager.cs: Android Call a non-static method

### ISSUE THREAD

**Issue by Darkness4** [snowballdigital/flutter-unity-view-widget#122]
Hello, I'm using unity 2019.3.7f1 with your plugin in the `master` branch. Unity cannot send message to Flutter on Android.

I think this is the problem: 

https://github.com/snowballdigital/flutter-unity-view-widget/blob/7010ee09e351796e9716cea7c815b01ac40a408c/scripts/unity_2019_3_5_later/UnityMessageManager.cs#L113-L114

Because `onUnityMessage` is a static method. 
Like for the older version of Unity, you may want to change to :

```C#
            AndroidJavaClass jc = new AndroidJavaClass("com.rexraphael.flutterunitywidget.UnityUtils");
            jc.CallStatic("onUnityMessage", message);
```

**Comment by Darkmax** [comment]
yes your are right changing to callstatic works

**Comment by juicycleff** [comment]
@Darkness4 your right, thanks for finding the bug. I am yet to test the latest release extensively on Android
