### ISSUE TITLE
Successed in emulator, but failed in real device

### ISSUE THREAD

**Issue by guoguoguilai** [snowballdigital/flutter-unity-view-widget#126]
Thanks for your amazing work!
I followed your README.md to set up an project. It really works in emulator and everything goes well. But when I install apk build from flutter in a real device, the APP just crashed.
Unity: 2019.1.0 and 2018.3.10f1
Flutter: 1.12.13+hotfix.8
Android SDK: 29.0.3
NDK: r16b
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.snowball.flutterappunity-XKoyNODxQHOCJl2khe0joA==/base.apk"],nativeLibraryDirectories=[/data/app/com.snowball.flutterappunity-XKoyNODxQHOCJl2khe0joA==/lib/arm64, /data/app/com.snowball.flutterappunity-XKoyNODxQHOCJl2khe0joA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libflutter.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
	at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:119
Thank you in advance!

**Comment by juicycleff** [comment]
@guoguoguilai did you set the target to device instead of emulator in Unity player settings

**Comment by guoguoguilai** [comment]
> @guoguoguilai did you set the target to device instead of emulator in Unity player settings

Thanks for your replying. This problem has been solved. I did something wrong in setting the target platform. Now it works pretty well.

**Comment by adam-fu** [comment]
I can reproduce this error and asked a friend to reproduce that on the example and DemoApp project.

I rund SDK 30.0.2 with NDK version 19.2.53 for that to get the error. Other SDK 30 combinations with ndk 
'20.1.5948944' and  '21.4.7075529' lead to issue described in #467 . 
@juicycleff maybe it is good to reopen? It fails in simulator also on that combination. and I would be curious what version @guoguoguilai run to get this error and how did they solve it.

So below my trace for ndk 19.2/53:

```E/FlutterLoader( 4585): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libflutter.so" not found
E/FlutterLoader( 4585): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/FlutterLoader( 4585): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/FlutterLoader( 4585): 	at java.lang.System.loadLibrary(System.java:1664)
E/FlutterLoader( 4585): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:116)
E/FlutterLoader( 4585): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:153)
E/FlutterLoader( 4585): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:148)
E/FlutterLoader( 4585): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/FlutterLoader( 4585): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/FlutterLoader( 4585): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/FlutterLoader( 4585): 	at java.lang.Thread.run(Thread.java:923)
```
