### ISSUE TITLE
AR Black Screen on Android in signed release

### ISSUE THREAD

**Issue by laravelian** [snowballdigital/flutter-unity-view-widget#129]
I've got our android app compiling from the flutter cli just fine, and flutter run --release works on my device just fine.  However, when I go to create the signed apk with the flutter build apk tool, the AR view has a few oddities:

1) It does not ask for camera permission, it automatically sets those permissions as denied when I go to the app info on the device settings.

2) Even after updating those settings, the AR scene comes in as a black screen.  I can hear the sound effects of the object in the scene, but I cannot see the camera view.

This ONLY happens when installing the signed version of the app.

Anyone have any ideas?

**Comment by juicycleff** [comment]
@laravelian if you haven't fixed this try setting permissions inside of unity, and also on flutter

**Comment by qargali** [comment]
I tried to get permission in Flutter and it gets it but Unity does not open dialog for the permission. If you have been able to solve this could you please share your solution to this issue

**Comment by qargali** [comment]
> @laravelian if you haven't fixed this try setting permissions inside of unity, and also on flutter



> I've got our android app compiling from the flutter cli just fine, and flutter run --release works on my device just fine. However, when I go to create the signed apk with the flutter build apk tool, the AR view has a few oddities:
> 
> 1. It does not ask for camera permission, it automatically sets those permissions as denied when I go to the app info on the device settings.
> 2. Even after updating those settings, the AR scene comes in as a black screen.  I can hear the sound effects of the object in the scene, but I cannot see the camera view.
> 
> This ONLY happens when installing the signed version of the app.
> 
> Anyone have any ideas?

I tried to get permission in Flutter and it gets it but Unity does not open dialog for the permission. If you have been able to solve this could you please share your solution to this issue

**Comment by laravelian** [comment]
This actually had to do with the unityandroidpermissions.aar file inside of UnityExport.  I had to replace it with the one here:

https://github.com/Over17/UnityAndroidPermissions/blob/master/Assets/Plugins/Android/unityandroidpermissions.aar

**Comment by timbotimbo** [comment]
I believe I fixed this another way, Iooking back at my commits from a while ago.
This should prevent the AndroidPermission from being stripped.

Enable a custom proguard file in unity. (The gradle checkbox isn't needed, this image is from the unity docs)
![unityproguard](https://user-images.githubusercontent.com/11444698/119803933-310fc180-bee0-11eb-86ff-8691518697bc.png)

Then place this in `Assets/Plugins/Android/proguard-user.txt`
```
-keep class com.unity3d.plugin.UnityAndroidPermissions** { *; }
-ignorewarnings

```
