### ISSUE TITLE
How to send binary data from memory to unity directly?

### ISSUE THREAD

**Issue by guoguoguilai** [snowballdigital/flutter-unity-view-widget#130]
Hello,
thank you so much for your amazing work ! 
I have such a requirement that I need to process the recorded video through Machine Learning,  then apply the processing results to the character model in unity, and play real-time video in unity.

There are two solutions: one is do the whole process of recording video, video processing and result application in unity, but the problem is that recording and player video in unity is troublesome, and machine learning is also troublesome on processing data.
The second is: 1.  record video in the flutter (there are a lot of plug-ins to process the video,), 2. use TFLite for flutter to process the video and output some useful information, 3. then send the information to the unity and drive the character model 4. play the video on canvas in unity at the same time.
I prefer the second one.  Do I have to record video and process it in unity? Is there any way to send every frame I record to unity in real time?

**Comment by laravelian** [comment]
I'm pretty sure the second option is going to be more troublesome than the first, and may not even be possible.  You'll likely have to record and process the video 100% from within unity.

**Comment by guoguoguilai** [comment]
> I'm pretty sure the second option is going to be more troublesome than the first, and may not even be possible. You'll likely have to record and process the video 100% from within unity.

Thank you for your answer. I'll try the first one.
