### ISSUE TITLE
iOS can't run example

### ISSUE THREAD

**Issue by artemsivcev** [snowballdigital/flutter-unity-view-widget#132]
Hey there! After start app on real device I see this:
```
2020-04-22 14:27:31.276102+0300 Runner[1397:695256] Metal API Validation Enabled
2020-04-22 14:27:31.414198+0300 Runner[1397:695426] flutter: Observatory listening on http://127.0.0.1:61644/YnUdKfVuyNQ=/
2020-04-22 14:27:32.113405+0300 Runner[1397:695256] Built from '2019.3/staging' branch, Version '2019.3.10f1 (5968d7f82152)', Build type 'Release', Scripting Backend 'il2cpp'
-> applicationDidFinishLaunching()

Setting UIViewControllerBasedStatusBarAppearance to NO is no longer supported.
Apple actively discourages that, and all application-wide methods of changing status bar appearance are deprecated

-> applicationDidBecomeActive()
-> applicationDidFinishLaunching()
ClassID 100000 (int) conflicts with that of another class (int). Please resolve the conflict. 
(Filename:  Line: 263)
```
Flutter doctor - ok
Android build and run - ok
Unity-IPhone/Data target - ok
Runner lib added from Unity-IPhone - ok
Other points from README - ok

Device IOS - 13.4.1
XCode - 11.4.1 
Target SDK (Unity/Xcode) - 11.0

**Comment by duytruong27** [comment]
It is because the `createPlayer` is called twice in UnityUtils. One possible work around:

- Add `static bool player_created = false;` after line 12 in UnityUtils.mm
- In the `(void)createPlayer:(void (^)(void))completed` method, change 
`  if (UnityIsInited()) {
        return;
    }
 `

to:

`
    if (UnityIsInited() || player_created) {
        return;
    }
    
    player_created = true;
`

**Comment by artemsivcev** [comment]
@duytruong27 thanks! Thats work now!!! But idk why flutter unity interface is on top of all flutter interface, but this is another question...

**Comment by JesperBllnbm** [comment]
Wow! Thanks, why is this not changed in the package?

**Comment by sinano1107** [comment]
> It is because the `createPlayer` is called twice in UnityUtils. One possible work around:
> 
> * Add `static bool player_created = false;` after line 12 in UnityUtils.mm
> * In the `(void)createPlayer:(void (^)(void))completed` method, change
>   ` if (UnityIsInited()) { return; } `
> 
> to:
> 
> `if (UnityIsInited() || player_created) { return; } player_created = true;`

I was faced with this problem and tried to solve it, but I couldn't locate "UnityUtils.mm" well. I'm not sure.

Could you please tell me the path?
If I wanted to, I'd also like an image before and after the code change... 😊

**Comment by sinano1107** [comment]
Sorry, I was able to solve this problem.
The path to "UnityUtils.mm" is
External Libraries / Flutter Plugins / flutter- unity-widget / iOS / Classes / UnityUtils.mm / UnityUtils.mm

Another thing I misunderstood is to do both of the above solutions.

Good luck 👍

**Comment by duytruong27** [comment]
> Another thing I misunderstood is to do both of the above solutions.

I forked the repository and made a fix there, you can have a look at:
https://github.com/duytruong27/flutter-unity-view-widget/blob/master/ios/Classes/UnityUtils.mm

But to me this is just a workaround, the proper solution would be adapting the UnityIsInited() method, but I don't have yet an idea to do..
