### ISSUE TITLE
Build successfully but get ClassNotFoundException when call method inside unity from flutter

### ISSUE THREAD

**Issue by guoguoguilai** [snowballdigital/flutter-unity-view-widget#133]
After export to Android, I got two .aar in Unity-Export/. I followed #101 to add .aar as library and it was successful. But when I call from flutter, it throwed such error below:
[  +12 ms] E/Unity   (21778): AndroidJavaException: java.lang.ClassNotFoundException: com.olokobayusuf.natcorder.MP4Recorder
[   +1 ms] E/Unity   (21778): java.lang.ClassNotFoundException: com.olokobayusuf.natcorder.MP4Recorder
[        ] E/Unity   (21778):   at java.lang.Class.classForName(Native Method)
[        ] E/Unity   (21778):   at java.lang.Class.forName(Class.java:454)
[        ] E/Unity   (21778):   at java.lang.Class.forName(Class.java:379)
[   +4 ms] E/Unity   (21778):   at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
[   +1 ms] E/Unity   (21778):   at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
[   +1 ms] E/Unity   (21778):   at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
[        ] E/Unity   (21778):   at android.os.MessageQueue.next(MessageQueue.java:405)
[   +6 ms] E/Unity   (21778):   at android.os.Looper.loop(Looper.java:174)
[   +1 ms] E/Unity   (21778):   at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
[        ] E/Unity   (21778): Caused by: java.lang.ClassNotFoundException: Didn't find class
"com.olokobayusuf.natcorder.MP4Recorder" on path: DexPathList[[zip file
"/data/app/net.jaggerwang.fip-Z_tYKhMHcTJxM9Xi5ANKJQ==/base.apk"],nativeLibraryDirectories=[/data/app/net.jaggerwang.fip-Z_tYKhMHcTJxM9Xi5ANKJQ==/lib/x86, /data/app/net.jaggerwang.fip-Z_tYKhMHcTJxM9Xi5ANKJQ==/base.apk!/lib/x86, /system/li

I built Android APK and it worked pretty good. 
How to solve this problem? Any help will be appreciated!

**Comment by subjectdenied** [comment]
i think you can fix this by using the
--no-shrink
cli-arg when building the app

**Comment by guoguoguilai** [comment]
Solved. I opened the project with Android Studio in the wrong folder, and then I drag the generated aar folder in the explorer instead of inside the AS. It might be the reference issue. I just move the aar folders into "android/" inside Android Studio, and it worked.
