### ISSUE TITLE
Unity will crash on Flutter 1.17 and any beta channel version

### ISSUE THREAD

**Issue by skypu3** [snowballdigital/flutter-unity-view-widget#138]
Hi, 

I got crash on iOS, the message is listed as below
ClassID 100000 (int) conflicts with that of another class (int). Please resolve the conflict. 
However, the older stable version 1.12 is fine, does anyone know about this issue ?

**Comment by skypu3** [comment]
```
UnityUpdateMuteState([audioSession outputVolume] < 0.01f ? 1 : 0);
// Modified by https://github.com/snowballdigital/flutter-unity-view-widget 
[[NSNotificationCenter defaultCenter] postNotificationName: @"UnityReady" object:self];
```
I found root cause that UnityReady event didn't be posted, and startUnity didn't be called, so it will init unity twice, then crash on RegisterAllClasses.
It is also happened on Flutter unity sample project.
However, the flutter 1.12 version with the Unity plugin, everything is normal, so maybe need to take look why startUnity didn't be called.

**Comment by skypu3** [comment]
I fixed the issue by directly call start unity method on UnityAppController.mm. 
``` 
 [self startUnity:application];
 // [self performSelector: @selector(startUnity:) withObject: application afterDelay: 0];
```
Then add below before InitUnity inside dispatch_async
```
if (_isUnityReady) {
  completed();
  return;
}
``` 
It can resolve the crash issue, however flutter ui can't show up on UnityView.
=> After insert unityview on FlutterUnityView, it will occupy whole screen, the flutter ui can't be saw.

**Comment by skypu3** [comment]
I fix crash issue by adding

**Comment by Darkmax** [comment]
it resolved, but the interaction with the unity view is null, I cannot interact with unity view even with the ui inside the unity app

**Comment by cogoo** [comment]
Where exactly do you need to place this code: 

```
if (_isUnityReady) {
  completed();
  return;
}
```

I cant seem to find the `_isUnityReady` variable.

**Comment by Darkmax** [comment]
> Where exactly do you need to place this code:
> 
> ```
> if (_isUnityReady) {
>   completed();
>   return;
> }
> ```
> 
> I cant seem to find the `_isUnityReady` variable.

Is on UnityUtils.mm file, around  line 156 of the file

**Comment by cogoo** [comment]
> > Where exactly do you need to place this code:
> > ```
> > if (_isUnityReady) {
> >   completed();
> >   return;
> > }
> > ```
> > 
> > 
> > I cant seem to find the `_isUnityReady` variable.
> 
> Is on UnityUtils.mm file, around line 156 of the file

Thanks! Main issue was locating the file itself. I was looking in the `UnityExport` folder. :(

**Comment by Darkmax** [comment]
is on flutter-unity-view-widget\ios\Classes

**Comment by skypu3** [comment]
> it resolved, but the interaction with the unity view is null, I cannot interact with unity view even with the ui inside the unity app

please check the https://github.com/flutter/flutter/issues/56660
it can resolve flutter ui issue with Unity.
The main reason platform uiview need to declare at initWithFrame method
Put the following code after [_channel setMethodCallHandler]
```swift
_uView = [[FlutterUnityView alloc] init];
if ([UnityUtils isUnityReady]) {
    [_uView setUnityView: (UIView*)[GetAppController() unityView]];
} else {
    [UnityUtils createPlayer:^{
         [_uView setUnityView: (UIView*)[GetAppController() unityView]];
    }];
    [GetAppController() setUnityMessageHandler: ^(const char* message)
    {
         [_channel invokeMethod:@"onUnityMessage" arguments:[NSString stringWithUTF8String:message]];
     }];
 }
```
Then only return uiview
```swift
- (UIView*)view {
    return _uView;
}
```

**Comment by Darkmax** [comment]
@skypu3 thanks, yes it resolve the issue. Thanks for the tip.

**Comment by TinyGiantDigital** [comment]
> > it resolved, but the interaction with the unity view is null, I cannot interact with unity view even with the ui inside the unity app
> 
> please check the [flutter/flutter#56660](https://github.com/flutter/flutter/issues/56660)
> it can resolve flutter ui issue with Unity.
> The main reason platform uiview need to declare at initWithFrame method
> Put the following code after [_channel setMethodCallHandler]
> 
> ```swift
> _uView = [[FlutterUnityView alloc] init];
> if ([UnityUtils isUnityReady]) {
>     [_uView setUnityView: (UIView*)[GetAppController() unityView]];
> } else {
>     [UnityUtils createPlayer:^{
>          [_uView setUnityView: (UIView*)[GetAppController() unityView]];
>     }];
>     [GetAppController() setUnityMessageHandler: ^(const char* message)
>     {
>          [_channel invokeMethod:@"onUnityMessage" arguments:[NSString stringWithUTF8String:message]];
>      }];
>  }
> ```
> 
> Then only return uiview
> 
> ```swift
> - (UIView*)view {
>     return _uView;
> }
> ```

Thanks for all of your work on this! Can you be more specific on where to put this code as i cant get it to work unfortunately :-(

**Comment by TinyGiantDigital** [comment]
> 
> Thanks for all of your work on this! Can you be more specific on where to put this code as i cant get it to work unfortunately :-(

Spoke too soon... i have it working! Remembering to refresh the pubspec.yaml !

**Comment by LucasTejero** [comment]
> > it resolved, but the interaction with the unity view is null, I cannot interact with unity view even with the ui inside the unity app
> 
> please check the [flutter/flutter#56660](https://github.com/flutter/flutter/issues/56660)
> it can resolve flutter ui issue with Unity.
> The main reason platform uiview need to declare at initWithFrame method
> Put the following code after [_channel setMethodCallHandler]
> 
> ```swift
> _uView = [[FlutterUnityView alloc] init];
> if ([UnityUtils isUnityReady]) {
>     [_uView setUnityView: (UIView*)[GetAppController() unityView]];
> } else {
>     [UnityUtils createPlayer:^{
>          [_uView setUnityView: (UIView*)[GetAppController() unityView]];
>     }];
>     [GetAppController() setUnityMessageHandler: ^(const char* message)
>     {
>          [_channel invokeMethod:@"onUnityMessage" arguments:[NSString stringWithUTF8String:message]];
>      }];
>  }
> ```
> 
> Then only return uiview
> 
> ```swift
> - (UIView*)view {
>     return _uView;
> }
> ```

This work for me but the answers its difficult,you have to move the first code below [_channel setMethodCallHandler],and then replace the method to only return the uView.

Thank you very much!!
