### ISSUE TITLE
Is there any working example

### ISSUE THREAD

**Issue by tsdevelopment** [snowballdigital/flutter-unity-view-widget#139]
I tried several examples but I get error after error. With the newest version of the plugin I get the following error:

```
error: no visible @interface for 'UnityAppController' declares
    the selector 'setUnityMessageHandler:'
            [GetAppController() setUnityMessageHandler: ^(const char* message)
             ~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~
```

So I tried the solution from this post: https://github.com/snowballdigital/flutter-unity-view-widget/issues/82#issuecomment-565432788 - but then I get several other errors. Is there any working example that I can use to the the plugin running in my app?

**Comment by tsdevelopment** [comment]
Okay, got it working with that script: https://github.com/juicycleff/flutter-unity-arkit-demo/blob/master/unity/ARDemoApp/Assets/Editor/XCodePostBuild.cs

**Comment by mortadda** [comment]
working example:
1- connect device with cpu : armeabi-v7a or arm64-v8a 
2- unzip downloaded project 
3- cd to project
4-flutter run


https://www.mediafire.com/file/695ez17nkk75i0g/flutter-unity-arkit-demo-master.zip/file

**Comment by tsdevelopment** [comment]
Thank you for the example. Seems to work. But I get the same error as mentioned here: #140 - so I think we have to wait until this will be fixed.
