### ISSUE TITLE
I can't get ios build

### ISSUE THREAD

**Issue by byferdi42** [snowballdigital/flutter-unity-view-widget#147]
There is no problem with Android scanning but I get an error on the iOS side. I did what was said on other topics, but nothing I did helped me get rid of the error, please help me get rid of the bug. Thank you now.

Note : sorry for my low level of english

Error :
>  ld: warning: directory not found for option '-F/Users/ferdi/flutterProjects/hisliFil/hislifil-abeb43a781304c4cf4f6deb3d6b340de481486a8/ios/Pods/../.symlinks/flutter/ios-release'
> ld: warning: ignoring file /Users/ferdi/Library/Developer/Xcode/DerivedData/Runner-epfuripqyugwgffpjzkhibqxpuuo/Build/Products/Debug-iphoneos/UnityFramework.framework/UnityFramework, building for iOS-armv7 but attempting to link with file built for iOS-arm64
> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_UnityAppController", referenced from:
>       objc-class-ref in FlutterUnityWidgetPlugin.o
>       objc-class-ref in UnityUtils.o
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by sinano1107** [comment]
I am having trouble receiving something very similar to this error message.
Please let me know how you resolved it.
