### ISSUE TITLE
Problem with keyboard on android when exit screen of unity

### ISSUE THREAD

**Issue by Darkmax** [snowballdigital/flutter-unity-view-widget#149]
Hi I'm having a problem on both platforms but is more present on android. 

When the user is exiting the view where unity is embedded, and clicks on a input field on flutter the keyboard appears but is not possible to be hidden. This problems happens if you load the unity view and then exit (pop) from this one. 

Also this error popups when I exit on android and ios:

> _Unhandled Exception: MissingPluginException(No implementation found for method dispose on channel unity_view_0)_

And when I run this command on flutter on the screen where the input field is present:
`MediaQuery.of(context).viewInsets.bottom` 

the keyboard return 0 height, and some people mention that this error happens if there are very complex widget tree, but this error only happens when I exit from the flutter screen that has the unity view.

So anyone had this error before? and know how to resolve it?

**Comment by gabrielchaves7** [comment]
I was having a similar issue. But I found a fixed for that: you have to edit the code inside the plugin, find the line "UnityUtils.getPlayer().quit();" and comment it (to avoid to close the entire app). And replace it for: 
activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);         activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
When I do that, I remove the full screen and my keyboard starts to work properly. But this remove your app from fullscreen.

**Comment by gabrielchaves7** [comment]
The dispose exception is not important, its just because the plugin devs didnt create a implementation for the dispose method call :D

**Comment by Darkmax** [comment]
thanks it works.

**Comment by Gadda27** [comment]
> I was having a similar issue. But I found a fixed for that: you have to edit the code inside the plugin, find the line "UnityUtils.getPlayer().quit();" and comment it (to avoid to close the entire app). And replace it for:
> activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN); activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
> When I do that, I remove the full screen and my keyboard starts to work properly. But this remove your app from fullscreen.

@gabrielchaves7 
Thanks for this, but it indeed removes the possibility to go fullscreen on other screens. This is a problem for my app. 
I tried to only add this line:
activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);

Although that restores the status bar just like I want, Flutter's _setSystemUiOverlays_ is somehow overriden and the statusbar is always automatically restored whenever i try to hide in another screen.

Do you have insight maybe on which flags one can set/remove to deal with this? 
Thanks!

**Comment by gabrielchaves7** [comment]
> > I was having a similar issue. But I found a fixed for that: you have to edit the code inside the plugin, find the line "UnityUtils.getPlayer().quit();" and comment it (to avoid to close the entire app). And replace it for:
> > activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN); activity.getWindow().addFlags(WindowManager.LayoutParams.FLAG_FORCE_NOT_FULLSCREEN);
> > When I do that, I remove the full screen and my keyboard starts to work properly. But this remove your app from fullscreen.
> 
> @gabrielchaves7
> Thanks for this, but it indeed removes the possibility to go fullscreen on other screens. This is a problem for my app.
> I tried to only add this line:
> activity.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
> 
> Although that restores the status bar just like I want, Flutter's _setSystemUiOverlays_ is somehow overriden and the statusbar is always automatically restored whenever i try to hide it in another screen.
> 
> Do you have insight maybe on which flags one can set/remove to deal with this?
> Thanks!

@Gadda27 
I think that this problem is related to the way that the plugin work, because they create an activity to show the unity but you cant dispose it, so this will always keep alive inside your app. This is why is only possible change the system overlays when you access the activity directly. You can try to uncomment the line "UnityUtils.getPlayer().quit();" and replace ".quit" for ".pause" maybe change something, but i dont know if will fix your problem.
