### ISSUE TITLE
Button doesn't detect tapping 

### ISSUE THREAD

**Issue by TarekMedhat** [snowballdigital/flutter-unity-view-widget#15]
Expected: I've a unity project with a button and a background, when the button is clicked the background image should change.

What's happening in flutter project: the button is not clickable at all, it doesn't detect the click even it's working fine on unity.

any solutions?

**Comment by lorant-csonka-planorama** [comment]
You should try the example project.
This solution uses `UnityMessageManager` to communicate between Unity and Flutter.
Your clicks/taps in the app are only handled at the flutter part, and you should figure out how to give them to the unity part.

**Comment by TarekMedhat** [comment]
Thank you @lorant-csonka-planorama for your response.
So all gestures are not detected by unity and all gestures should be handled by gesturedetector widgets on flutter? I mean if I am building a puzzle game I won't be able to handle gestures on unity?

**Comment by lorant-csonka-planorama** [comment]
Yes, that's how it works. You have to implement the communication layer between flutter and unity, and that includes interactions also.

**Comment by thomas-stockx** [comment]
@lorant-csonka-planorama I've been investigating this a bit on Android but hitting a bit of a dead end.

Do you know why the UnityView does not get any touch events, while other native AndroidViews (such as the GoogleMaps and WebView plugins) do? I've been trying to catch them at the FrameLayout level and passing them through to the UnityPlayer (as the default UnityPlayerActivity class does), but I can't even get the user interaction to register on that level.

**Comment by thomas-stockx** [comment]
Fixed in https://github.com/snowballdigital/flutter-unity-view-widget/pull/16!

Since the maintainer of this repo doesn't seem to merge my pull requests, there is a branch with several fixes available here:
https://github.com/thomas-stockx/flutter-unity-view-widget/tree/improvements

**Comment by TarekMedhat** [comment]
> Fixed in #16!
> 
> Since the maintainer of this repo doesn't seem to merge my pull requests, there is a fork with several fixes available here (use the improvements branch):
> https://github.com/thomas-stockx/flutter-unity-view-widget/tree/improvements

Well done, You did a very nice job, thanks for sharing that.
Do you have any clue on the progress with the IOS? did you investigate in this?

**Comment by thomas-stockx** [comment]
@TarekMedhat Yes, we (@krispypen and myself) are currently investigating iOS and Unity AR Foundation support and we're seeing some progress. We'll hopefully have more to share about it later this week. However, expect baby steps for the iOS version! We first need to get a Unity scene to work, and then try to get feature parity with the Android version (touch, AR support,...)
