### ISSUE TITLE
Export to Android (flutter) error

### ISSUE THREAD

**Issue by mrctrl69** [snowballdigital/flutter-unity-view-widget#154]
Hey,
Slim here

I wonder if someone having same issue with me or solved already and willing to help me.

I was following the tuts from [](https://pub.dev/packages/flutter_unity_widget) untill i get stuck at the exporting part which gave me this error

> DirectoryNotFoundException: Could not find a part of the path 'S:\Codes\Projects\Flutter\vreals\unity\Kovee-AR-master\Builds\Kovee AR Project Unity 2019.apk\vreals'.
System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].HandleError (System.Int32 hr, System.String path) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource].CommonInit () (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableIterator`1[TSource]..ctor (System.String path, System.String originalUserPath, System.String searchPattern, System.IO.SearchOption searchOption, System.IO.SearchResultHandler`1[TSource] resultHandler, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.FileSystemEnumerableFactory.CreateFileNameIterator (System.String path, System.String originalUserPath, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.InternalGetFileDirectoryNames (System.String path, System.String userPathOriginal, System.String searchPattern, System.Boolean includeFiles, System.Boolean includeDirs, System.IO.SearchOption searchOption, System.Boolean checkHost) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.InternalGetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <437ba245d8404784b9fbab9b439ac908>:0)
System.IO.Directory.GetDirectories (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <437ba245d8404784b9fbab9b439ac908>:0)
Build.Copy (System.String source, System.String destinationPath) (at Assets/Editor/Build.cs:91)
Build.DoBuildAndroid () (at Assets/Editor/Build.cs:42)
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()

Any idea?

**Comment by juicycleff** [comment]
This looks like an issue with Unity and not the lib

**Comment by mrctrl69** [comment]
Yeah, i managed to fix this by reprogressing from my checkpoint, and it's good now, thanks mate for paying attention
