### ISSUE TITLE
Unity to Flutter Message not working in released apk/bundle - Android

### ISSUE THREAD

**Issue by TarekMedhat** [snowballdigital/flutter-unity-view-widget#157]
Unity to flutter messaging working fine using flutter run commands but not for building apk/bundle.
**I am able to receive messages using**

- flutter run --debug

- flutter run --release

**But for released apk/bundle messages simply doesn't work** 

- flutter build apk --release

- flutter build appbundle

I've tried on both the example project and mine and couldn't get it to work.
I'm on unity 2019.3.13

**Comment by TarekMedhat** [comment]
Can anyone confirm if it worked with him?
I've tried 2019.3.5f1 but still the same..

**Comment by sarawin008** [comment]
It work fine for me on Unity 2019.3.7f1 and flutter 1.17.2 both message from unity to flutter and flutter to unity in release apk. maybe u can try build using : flutter build apk --no-shrink    hope it help.

**Comment by TarekMedhat** [comment]
> It work fine for me on Unity 2019.3.7f1 and flutter 1.17.2 both message from unity to flutter and flutter to unity in release apk. maybe u can try build using : flutter build apk --no-shrink hope it help.

Actually it worked using --no-shrink thank you, I also could get it to work by using "Generate Signed APK/Bundle" directly from android project using android-studio instead of using the generated  apk from "flutter build".
