### ISSUE TITLE
Importing VuforiaWrapper.aar to project

### ISSUE THREAD

**Issue by mrctrl69** [snowballdigital/flutter-unity-view-widget#158]
I've tried the instructions from scratch for the Vuforia and now stuck on this **bolded** problem:

> Vuforia
Android

Similar to setting up AR Foundation, but creating a module for the VuforiaWrapper instead.

Thanks to @PiotrxKolasinski for writing down the exact steps:

1. Change in build.gradle: implementation(name: 'VuforiaWrapper', ext:'aar') to implementation project(':VuforiaWrapper')
2. In settings.gradle in the first line at the end add: ':VuforiaWrapper'
**3. From menu: File -> New -> New Module choose "import .JAR/.AAR Package" and add lib VuforiaWrapper.arr. Move generated folder to android/**
4. In Widget UnityWidget add field: isARScene: true
5. Your App need camera permission (you can set in settings on mobile)

on my android studio, everytime i tried to import the file, it always say:

> Can't understand Gradle settings file, please add the path ':VuforiaWrapper' manually.

also, i tried this [https://github.com/snowballdigital/flutter-unity-view-widget/issues/111](url)
but still not? working for me or it's my miss-understanding about what code to type where.

hope i get assistant here,
Regards, Slim

**Comment by ElDuderini** [comment]
If you managed to get this to work, I would love to know how you did it. I haveb been trying to do the same thing but for some other plugins for my unity project with the same message.

**Comment by LaloBerro** [comment]
hi! any solution?

**Comment by mrctrl69** [comment]
Oh, hey @ElDuderini @LaloBerro 
I've been off lately

I'm still afk rn, i'll update this comment ASAP

**Comment by LaloBerro** [comment]
@mrctrl69 hey!, thanks i would really appreciate it

**Comment by planetMatrix** [comment]
> Oh, hey @ElDuderini @LaloBerro
> I've been off lately
> 
> I'm still afk rn, i'll update this comment ASAP

Hi @mrctrl69 we would appreciate if you could share the solution.

Many thanks

**Comment by planetMatrix** [comment]
I got it working by importing VuforiaWrapper via modules in project structure
![Screenshot 2020-12-05 at 2 00 33 PM](https://user-images.githubusercontent.com/38416064/101237912-7954e080-3702-11eb-9388-11375788c5ce.png)

**Comment by MtPython** [comment]
I solved this problem by getting the [FlutterUnityPackage-3.0.0.unitypackage](https://github.com/juicycleff/flutter-unity-view-widget/blob/master/scripts/FlutterUnityPackage-3.0.0.unitypackage) by cloning the full repo to disk, and then importing the file from there. A direct download from browser generated a file of ~100KB, but a correct file should be ~640KB.
