### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by mrctrl69** [snowballdigital/flutter-unity-view-widget#159]
> Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* Where:
Build file 'S:\Codes\Projects\Flutter\vreals\android\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [file collection] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

why I'm still having stil error? Is that a problem with the .jar file or something?
in this case, i tried to import the .jar to my project manually using the instruction i found in other's closed issue, since my Android Studio > Add as Library not working (nothing happen after i clicked OK), maybe that's the problem? i missing something?

Regards,
Slim

**Comment by ROBYER1** [comment]
What was the fix for this?
