### ISSUE TITLE
Android - onUnityMessage not working on Release (Work well on debug)

### ISSUE THREAD

**Issue by phamtuongvan** [snowballdigital/flutter-unity-view-widget#172]
flutter_unity_widget: 0.1.6+8

Build example projectile but onUnityMessage not working on Release (Work well on debug)
void Update()
    {
        gameObject.transform.Rotate(RotateAmount * Time.deltaTime * 10);

        for (int i = 0; i < Input.touchCount; ++i)
        {
            if (Input.GetTouch(i).phase.Equals(TouchPhase.Began))
            {
                var hit = new RaycastHit();

                Ray ray = Camera.main.ScreenPointToRay(Input.GetTouch(i).position);

                if (Physics.Raycast(ray, out hit))
                {
                    // This method is used to send data to Flutter
                    UnityMessageManager.Instance.SendMessageToFlutter("The cube feels touched.");
                }
            }
        }
    }

void onUnityMessage(controller, message) {
    print('Received message from unity: ${message.toString()}');
 }

**Comment by alexxlagutin** [comment]
@phamtuongvan 
Hi! Did you find solution on this?

**Comment by TarekMedhat** [comment]
@alexxlagutin I had the same issue and fixed it by doing `flutter build appbundle` as usual, but then I head to flutterproject/android and open it with Android Studio and regenerate the apk directly from the Android project instead, by "Generate Signed APK/Bundle" from build menu, the generated apk worked fine.

Another way: `flutter build apk --release --no-shrink` also worked for me but the apk size was slightly bigger than the first apporach.

So I believe it might be an issue with the R8 shrink, you might consider using proguard instead.

**Comment by alexxlagutin** [comment]
@TarekMedhat 
Thanks! That works for me!

**Comment by subzero911** [comment]
This problem returns after migrating to latest 4.2.1 version.
Solutions, provided above, didn't work for us.
We use `--no-shrink` flag. I also unticked "strip engine code" in Unity, but it had no effect.
We can't compile it manually from AS, as we use Codemagic CI.
