### ISSUE TITLE
IOS build ,XCode report:ClassID 100000(int) conflicts with that of another class (int)

### ISSUE THREAD

**Issue by sohubill** [snowballdigital/flutter-unity-view-widget#178]
When building ios, a title error occurs, and the program crash；

The solution：
1、click #import "UnityUtils.h" and jump to Definition to "UnityUtils.h";
2、click function InitUnity() and jump to Definition to "UnityUtils.mm";
3、Find dispatch_async and locate to dispatch_async "dispatch_get_main_queue(),...});"
4、Add code before " InitUnity ()" : if(_isUnityReady){
                                                           completed();
                                                           return;
                                                      }
5、add code after " bool unity_inited=false;",about  at 12 lines:"static bool player_created=false;"
6、Replace code
" if (UnityIsInited()) {
        return;
    }
 " 
in method "+(void)createPlayer" with code :
" if (UnityIsInited()||player_created) {
        return;
    }
    player_created=true;
"

**Comment by juicycleff** [comment]
Please properly format your issue and also help us understand your problem :)

**Comment by subjectdenied** [comment]
this is about the issue in / a duplicate of #132
