### ISSUE TITLE
Questions on the postMessage API

### ISSUE THREAD

**Issue by kiannc** [snowballdigital/flutter-unity-view-widget#182]
Hello,

I have some question regarding the postMessage API.
For example, i have 2 screens. Screen A and Screen B (Will launch unity)
Screen A will then pass some data on to Screen B. In order to pass the data obtain from Screen A into Unity,
Can the postMessage API be used in initState of flutter or do i have to wait until unity has finished loading?

Thank you

**Comment by Jatin-Pawar** [comment]
@kiannc Were you able to solve this issue? If yes, kindly share your findings. 👍

**Comment by juicycleff** [comment]
You have to wait until the unity screen of course. Also, you should be able to post to a screen afterward. One way to solve this is to load Unity Widget in the background and bring the widget back to view when you need to.

**Comment by kiannc** [comment]
Hi Juicycleff,

Thank for the explaination, Will give it a try.

Hi @Jatin-Pawar ,

What i end up doing is, after the Unity finish loading, in the awake function of unity i will send a message (eg: 'unityLoaded') from unity to flutter telling flutter that has finish loading. Then on the flutter side, using the onUnityMessage i will check for the message if its the same message i sent over then i proceed to send message from flutter into unity.
