### ISSUE TITLE
Fade transition to flutter unity widget causing a “blip” on first time loading

### ISSUE THREAD

**Issue by OGmetamonkey** [snowballdigital/flutter-unity-view-widget#184]
I have a button on a page that push navigates to a second page with a Custom Page Route and Fade Transition. 

**First page:**

    InkWell(
                onTap: () {
                  final page = SecondPage();
                      Navigator.of(context).push(CustomPageRoute(page));
                },

    class CustomPageRoute<T> extends PageRoute<T> {
          CustomPageRoute(this.child);
          @override
          // TODO: implement barrierColor
          Color get barrierColor => Color(0xff252926);
    
          @override
          String get barrierLabel => null;
    
          final Widget child;
    
          @override
          Widget buildPage(BuildContext context, Animation<double> animation,
    
              Animation<double> secondaryAnimation) {
            return FadeTransition(
              opacity: animation,
              child: child,
            );
          }
    
          @override
          bool get maintainState => true;
          @override
          Duration get transitionDuration => Duration(seconds: 2);
        }

The second page takes time to load a [flutter_unity_widget][1] on the initial load. I added the transition to take some of the flashing from the loading out of the UI. The below build function shows the second page operations in their most basic form.

**Second Page:**

    @override
      Widget build(BuildContext context) {
    
          return Scaffold(
            key: _scaffoldKey,
            // appBar: AppBar(
            //   title: const Text('Mindpass'),
            // ),
              body: Card(
              //border all around for Unity View
               margin: const EdgeInsets.all(0),
    
                  child:
                  UnityWidget(
                    onUnityViewCreated: onUnityCreated,
                    isARScene: false,
                    onUnityMessage: onUnityMessage,
                  ),
    
                ),  
          );
              
      }

This transition works smoothly on the 2nd and following tries, but on the first try it always blips to a black screen and ignores the transition.

**Attempts to fix:**
1. I have tried using Visibility and Stack in the second page build function to provide a background box and make the UnityWidget (over the box in the stack) invisible for a few seconds, but it still blips to a black screen and ignores the transition on the first load, and works as expected on the following tries once unity is loaded. 

2. I also tried using Visibility in the flutter_unity_widget itself in the same way as above and got the same results.

Why is the loading of the module causing the app to ignore the transition, and/or how can I fix it?

  [1]: https://pub.dev/packages/flutter_unity_widget

**Comment by OGmetamonkey** [comment]
Anybody else having this issue?

**Comment by MuazamAli69** [comment]
> Anybody else having this issue?

Can you please help me for running this project successfully or share running sample with me. I am really thankful for this favour.

**Comment by juicycleff** [comment]
@OGmetamonkey try loading unity in the background while your app is starting and keep it hidden. You can always bring it into view afterward. You need to understand that starting unity is an expensive operation

**Comment by MuazamAli69** [comment]
Thank you soo much sir for your feedback. i will check and ping you back,
