### ISSUE TITLE
How to not load flutter_unity_widget when running IOS simulator

### ISSUE THREAD

**Issue by alexxlagutin** [snowballdigital/flutter-unity-view-widget#188]
Hi!
Im developing an app and one of its parts should use unity. But adding flutter_unity_widget as a dependency in Xcode blocks whole app to run in simulator. Is there any way to not load it when debugging not on real device?

**Comment by juicycleff** [comment]
@alexxlagutin there is no other way as the library will try to load it every time for now. Maybe that might change in the future but was designed that way for now. We can reopen this if we need to change this behavior

**Comment by TarekMedhat** [comment]
A workaround solution in order to be able to test non-unity part freely on simulator is by creating 2 git branches one with unity (dev) and another without (dev_no_unity). Do all your debugging/coding for non-unity part on dev_no_unity and later merge into dev.
That's the best way I could came up with to workaround it.

**Comment by alexxlagutin** [comment]
@TarekMedhat 
That is exactly what i do now. But as for me this is very uncomfortable.

**Comment by alexxlagutin** [comment]
@juicycleff 
This behaviour is ok if you make unity-only application. But when app grows to something bigger - it starts to be a problem.
If you can change this behaviour in the future - it would be great!

Anyway thank you for the plugin!

**Comment by PhiFry** [comment]
@TarekMedhat @alexxlagutin How did you go about disabling Unity in your side-branches? Did you simply remove flutter_unity_widget in pubspec.yaml? That creates build errors in the project and isnt runnable, or have you done something else that doesnt require almost a complete refactor?

**Comment by juicycleff** [comment]
> @juicycleff 
> 
> This behaviour is ok if you make unity-only application. But when app grows to something bigger - it starts to be a problem.
> 
> If you can change this behaviour in the future - it would be great!
> 
> 
> 
> Anyway thank you for the plugin!

So just to be clear, the limitation comes from Unity directly and not the package
