### ISSUE TITLE
Unable to build the iOS archive

### ISSUE THREAD

**Issue by sinano1107** [snowballdigital/flutter-unity-view-widget#189]
Now let's release the app! When I tried to build the archive, I got this error at the last minute.
There were several similar issues, but I was unable to solve them.
Please help me out.

Thanks in advance.

```
Undefined symbols for architecture armv7:
  "_InitArgs", referenced from:
      Runner.AppDelegate.application(_: __C.UIApplication, didFinishLaunchingWithOptions: [__C.UIApplicationLaunchOptionsKey : Any]?) -> Swift.Bool in AppDelegate.o
  "_OBJC_CLASS_$_FlutterUnityWidgetPlugin", referenced from:
      objc-class-ref in GeneratedPluginRegistrant.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

<img width="1440" alt="スクリーンショット 2020-08-10 9 50 39" src="https://user-images.githubusercontent.com/45984123/89745454-f5417200-daee-11ea-8d94-0f7788ca9510.png">

**Comment by alexxlagutin** [comment]
Same issue. Any suggestions?

**Comment by zin9x** [comment]
Me too, i'm build debug on android and ios, it worked but not build release 
Version  flutter_unity_widget: ^0.1.6+8 
Please support this issue,
Thanks!!!!

**Comment by sinano1107** [comment]
I was able to resolve this issue by setting Targets => Build Settings => Architectures => Architectures to 'arm64'.

Seems I had to do this because I'm using ARFoundation in unity.
But it's odd that it works correctly with a normal Run.

<img width="1440" alt="スクリーンショット 2020-08-10 22 43 39" src="https://user-images.githubusercontent.com/45984123/89789349-70407200-db5b-11ea-8f6b-ebad9ad21034.png">

I hope this solution helps 👍
