### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vaclavpavlicek** [snowballdigital/flutter-unity-view-widget#3]
Are you planning to write documentation or should I take a look at it?

**Comment by juicycleff** [comment]
Hi, @vaclavpavlicek I wrote the docs, but yes any help is welcomed.

**Comment by kerberjg** [comment]
This issue can be closed now. Thank you @juicycleff for your amazing work! 👍 ✨

**Comment by vaclavpavlicek** [comment]
Amazing, thank you! I will try it to implement it tommorow.

**Comment by juicycleff** [comment]
This issue has been resolved
