### ISSUE TITLE
IOS flutter_unity_widget build failed (UnityAppController)

### ISSUE THREAD

**Issue by TarekMedhat** [snowballdigital/flutter-unity-view-widget#32]
I'm having the following errors while building the IOS after following the documentation steps.
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_UnityAppController", referenced from:
      objc-class-ref in FlutterUnityWidgetPlugin.o
      objc-class-ref in UnityUtils.o
ld: symbol(s) not found for architecture x86_64`
Another project:
`Undefined symbols for architecture x86_64:
  "_GetAppController", referenced from:
      -[FUController view] in FlutterUnityWidgetPlugin.o
      ___20-[FUController view]_block_invoke in FlutterUnityWidgetPlugin.o
      +[UnityUtils handleAppStateDidChange:] in UnityUtils.o
      ___27+[UnityUtils createPlayer:]_block_invoke.68 in UnityUtils.o
ld: symbol(s) not found for architecture x86_64`
any clues?

**Comment by juicycleff** [comment]
Hi @TarekMedhat you exported you unity project for the wrong architecture. Please make sure if you are exporting to test on Real Device, remove the UnityExport reference in Xcode, before exporting

**Comment by juicycleff** [comment]
I will just go ahead and close this.

**Comment by SashaFarkas** [comment]
@juicycleff Could you please specify, how to remove UnityExport reference?

**Comment by WouterVandenputte** [comment]
> @juicycleff Could you please specify, how to remove UnityExport reference?

Would love to be able to fix this too. Have you found it yet @SashaFarkas ?
