### ISSUE TITLE
how to set the pop out button in flutter unity

### ISSUE THREAD

**Issue by azcodia** [snowballdigital/flutter-unity-view-widget#33]
how to change the appearance of the popup out and title apps flutter with unity

**Comment by thomas-stockx** [comment]
Hi @azcodia, can you be a bit more clear in what you try to achieve?

**Comment by azcodia** [comment]
sorry, so I already have a popup display, and this pop up appears if I want to exit unity, the problem that appears is the size of the popup display is too small, and I want to change the size of my popup, which is my question, can I change the size of this popup on flutter, or should I change it to unity?

**Comment by thomas-stockx** [comment]
If you're rendering the popup in Unity, you should change the scale in Unity. If it's a Flutter popup, you should change the size in Flutter. Both Unity and Flutter run completely independent of each other, they just allow communication between the two environments.
