### ISSUE TITLE
Clicking inputfield in Unity does not open keyboard (and enable the inputfield?)

### ISSUE THREAD

**Issue by rafbanaan** [snowballdigital/flutter-unity-view-widget#34]
With my Unity game I have a scene where a user can fill in an username and email address. These two last items are inputfields, but I'm having issues with this.

When I click on the inputfields nothing happens. I don't see a cursor in the inputfield and the keyboard doesn't pop up.

When I build it native for android it works. 

Any tips or is this a bug? I can't find a solution in Unity especially  when the native android build works perfect. I do have a 6 buttons in this scene and those work.. in the sense that I can click them and they activate.

**Comment by juicycleff** [comment]
@rafbanaan I believe this will not work for now and it's not an issue from unity, I am suggesting you use events to show the keyboard and see if input works ok

**Comment by rafbanaan** [comment]
Ok, I will give it a try with the events.

**Comment by thomas-stockx** [comment]
Most Unity games will actually use a native TextField (iOS or Android) since there's better support for copy/paste/etc, and send the result back to Unity.

You can do something similar by allowing Unity to trigger a Flutter TextField (with keyboard), and send the resulting input back to Unity to continue your game. That way you don't need to handle any text input in Unity, but handle it all in Flutter!

**Comment by rafbanaan** [comment]
So, if I read it correctly it's more common that in my case I convert my start scene with the inputfields and button into a flutter page which sends the results back to Unity?

**Comment by thomas-stockx** [comment]
@rafbanaan exactly! You can build your login/registration screen in Flutter, and after authentication you can navigate to a new Flutter page with Unity embedded, and send any authentication details through to Unity so it does not need to render any UI.

**Comment by rafbanaan** [comment]
@thomas-stockx Is there any documentation on the postMessage method? How to call it in flutter and how to accept the message in Unity. I can't find an example in the example project.

**Comment by thomas-stockx** [comment]
@rafbanaan https://github.com/snowballdigital/flutter-unity-view-widget/issues/31#issuecomment-521959945

**Comment by rafbanaan** [comment]
Got it working, thanks for the help!

Might be useful to put that example in the readme? Together with an example for unity to flutter?

**Comment by AkhilRaja** [comment]
> @rafbanaan I believe this will not work for now and it's not an issue from unity, I am suggesting you use events to show the keyboard and see if input works ok

Is there an update on this? My use case requires me to take user input from a unity view in iOS. Do you have a workaround for this ?
