### ISSUE TITLE
Failed to initialize Vuforia Engine

### ISSUE THREAD

**Issue by kamlesh9070** [snowballdigital/flutter-unity-view-widget#37]
I have made Unity Project with Vuforia and It is working in mobile by "Build and Run" in Unity Editor.

Now I am integrating same project in Flutter so I have exported project to flutter.

**I am facing below issue:**
 `I/Unity   ( 3247): Vuforia.PlatformRuntimeInitialization:InitPlatform()
I/Unity   ( 3247):
I/Unity   ( 3247): (Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
I/Unity   ( 3247):
E/Unity   ( 3247): **NullReferenceException: Object reference not set to an instance of an object.**
E/Unity   ( 3247):   at **Vuforia.AndroidDatasets.AddExternalDatasetSearchDirs** () [0x00000] in <00000000000000000000000000000000>:0
E/Unity   ( 3247):   at Vuforia.PlatformRuntimeInitialization.InitPlatform () [0x00000] in <00000000000000000000000000000000>:0
E/Unity   ( 3247):
E/Unity   ( 3247): (Filename: currently not available on il2cpp Line: -1)
E/Unity   ( 3247):
I/Unity   ( 3247): Initializing Vuforia Engine
I/Unity   ( 3247): UnityEngine.Logger:Log(LogType, Object)
I/Unity   ( 3247): Vuforia.VuforiaRuntime:InitVuforia()`

![Screenshot_20190830-085853](https://user-images.githubusercontent.com/16913432/63991864-01fbce80-cb07-11e9-8a9b-52649d8edf00.png)

Unity Export Folder : https://drive.google.com/open?id=1zipwU1nZchGI4BpytKbOU4juwtIHz3zH

Let me know if any more information is required.

**Comment by kamlesh9070** [comment]
@juicycleff  Waiting your reponse for this issue.

**Comment by jeromenicholas07** [comment]
Is there any explanation or solution for this?! @thomas-stockx

**Comment by thomas-stockx** [comment]
I've never used this with Vuforia, only with AR Foundation (Unity's wrapper around ARCore and ARKit). According to the docs @juicycleff has had this working at some point, so he should know what's going on.

**Comment by juicycleff** [comment]
I will take a look at it

**Comment by jeromenicholas07** [comment]
@juicycleff Thanks man

**Comment by PiotrxKolasinski** [comment]
1. Change in file build.gradle: implementation(name: 'VuforiaWrapper', ext:'aar') to implementation project(':VuforiaWrapper')
2. In settings.gradle in the first line at the end add: ':VuforiaWrapper'
3. From menu: File -> New -> New Module choose "import .JAR/.AAR Package" and add lib VuforiaWrapper.arr. Move generated folder to android/
4. In Widget UnityWidget add field: isARScene: true
5. Your App need camera permission (you can set in settings on mobile)

**Comment by thomas-stockx** [comment]
Thanks Piotrx, I'll add those steps in the README :)

**Comment by thomas-stockx** [comment]
closed by 521c84f

**Comment by mrctrl69** [comment]
I get this problem not solved by the above answer,

My first run on the app just runs fine,
But seconds and more, when i tried to open the Unity widget screen on my app, it crashed and show the same message as this post,

Here's my case,
*Working
1. Open freshly installed app
2. Open the unity scene screen
3. App ask for camera permission (grant it)
4. The scene opened

*Not working
1. Open again the app i mentioned
2. Open the unity scene again
3. The error pops up

*Solution
1. Open app info and ungrant the camera permission
2. Open the app again like it freshly installed, and the *working steps work

I find out the vuforia or the unity itself requesting for Camera Permission in order to initiate, any way to fix this? Or disable the permission? Or something?

Please help me on how to solve this, it's so annoying to ungrant the camera permission everytime i open the app

**Comment by qqmikey** [comment]
any solutions?

**Comment by mrctrl69** [comment]
@qqmikey mine still not solved, the only thing i could do is just ungrant the camera permission of my app, open the app, then let the vuforia engine ask to turn it on again

**Comment by faedarnob** [comment]
@slimmziy I am facing the exact same thing. Any update? 
First run works fine but re-running from the recent apps show error .

**Comment by NanTanjung** [comment]
> Saya mendapatkan masalah ini tidak terselesaikan dengan jawaban di atas,
> 
> Peluncuran pertama saya pada aplikasi berjalan dengan baik, Namun beberapa detik dan lebih lagi, ketika saya mencoba membuka layar widget Unity di aplikasi saya, aplikasi tersebut membuat dan menampilkan pesan yang sama seperti postingan ini,
> 
> Inilah kasus saya, *Bekerja
> 
> 1. Buka aplikasi yang baru diinstal
> 2. Buka layar adegan kesatuan
> 3. Aplikasi meminta izin kamera (berikan)
> 4. Adegan terbuka
> 
> *Tidak berfungsi
> 
> 1. Buka lagi aplikasi yang saya sebutkan
> 2. Buka kembali adegan persatuan
> 3. Kesalahan muncul
> 
> *Larutan
> 
> 1. Buka info aplikasi dan batalkan izin kamera
> 2. Buka kembali aplikasi seperti baru diinstal, dan *langkah kerja berfungsi
> 
> Saya menemukan vuforia atau kesatuan itu sendiri yang meminta Izin Kamera untuk memulai, adakah cara untuk memperbaikinya? Atau mengaktifkan izinnya? Atau sesuatu?
> 
> Tolong saya bantu tentang cara mengatasi ini, sangat mengganggu jika tidak memberikan izin kamera setiap kali saya membuka aplikasi



> Saya mendapatkan masalah ini tidak terselesaikan dengan jawaban di atas,
> 
> Peluncuran pertama saya pada aplikasi berjalan dengan baik, Namun beberapa detik dan lebih lagi, ketika saya mencoba membuka layar widget Unity di aplikasi saya, aplikasi tersebut membuat dan menampilkan pesan yang sama seperti postingan ini,
> 
> Inilah kasus saya, *Bekerja
> 
> 1. Buka aplikasi yang baru diinstal
> 2. Buka layar adegan kesatuan
> 3. Aplikasi meminta izin kamera (berikan)
> 4. Adegan terbuka
> 
> *Tidak berfungsi
> 
> 1. Buka lagi aplikasi yang saya sebutkan
> 2. Buka kembali adegan persatuan
> 3. Kesalahan muncul
> 
> *Larutan
> 
> 1. Buka info aplikasi dan batalkan izin kamera
> 2. Buka kembali aplikasi seperti baru diinstal, dan *langkah kerja berfungsi
> 
> Saya menemukan vuforia atau kesatuan itu sendiri yang meminta Izin Kamera untuk memulai, adakah cara untuk memperbaikinya? Atau mengaktifkan izinnya? Atau sesuatu?
> 
> Tolong saya bantu tentang cara mengatasi ini, sangat mengganggu jika tidak memberikan izin kamera setiap kali saya membuka aplikasi

Has a solution been found?
