### ISSUE TITLE
Project with path ':UnityExport' could not be found in project ':flutter_unity_widget'

### ISSUE THREAD

**Issue by GabrielMMI** [snowballdigital/flutter-unity-view-widget#39]
Hello, I'm using this framework and when I put 

> flutter_unity_widget: ^0.1.6+2

 in `android/pubspec.yalm` and run the app, occurred this error:

![image](https://user-images.githubusercontent.com/26382676/64214243-1123a900-ce86-11e9-94ec-2d97050769e6.png)

I tried to configure the project as shown in the tutorial, I am using Unity 2019.3.0a11, can you help me?

**Comment by juicycleff** [comment]
Please, you should properly configure the project. You didn't export the Android Unity project correctly

**Comment by juicycleff** [comment]
Follow this video https://www.youtube.com/watch?v=exNPmv_7--Q

**Comment by jamontes79** [comment]
Hello, I'm creating a project from scratch following the tutorial in github and the video in youtube and I'm getting the same error: Project with path ':UnityExport' could not be found in project ':app'.

When I select the option "add as library" fro unity-classes.jar nothing happend.

Any idea what I'm doing wrong?

Thanks in advance
Regards
