### ISSUE TITLE
why not to choose mono scripting backend ?

### ISSUE THREAD

**Issue by wangjianpeng** [snowballdigital/flutter-unity-view-widget#4]
if i want to use this plugin, why can't choose mono scripting backend with unity build ?

**Comment by kerberjg** [comment]
Is there any advantage of using Mono over IL2CPP?

**Comment by wangjianpeng** [comment]
the unity built project  can cost  much shorter  timer with mono than IL2CPP, it will save my develop time

**Comment by juicycleff** [comment]
@wangjianpeng at this point, the IL2CPP seems to be the most stable way of getting it to work. Something about how unity player is compiled using mono that gets some methods missing. I will still be improving and be writing iOS support, so I am looking to test it against mono intensively till I get a working implementation.

**Comment by juicycleff** [comment]
Tested with mono, and everything works well using Unity 2018.3.f12
