### ISSUE TITLE
java.lang.ClassNotFoundException when sending a message from Unity to Flutter (Android)

### ISSUE THREAD

**Issue by timonvw** [snowballdigital/flutter-unity-view-widget#41]
I get this error in the debug console (Android Studio) when I send a message in Unity to Flutter.

Error:

`E/Unity   ( 8367): java.lang.ClassNotFoundException: Didn't find class "com/reactnative/unity/view/UnityUtils" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/lib/arm64, /data/app/com.rexraphael.flutterunitywidgetexample-A3IZZoUXENEbVBkqDGNLAQ==/base.apk!/lib/arm64-v8a, /system/lib`

![image](https://user-images.githubusercontent.com/14540114/64381015-89c76880-d032-11e9-9853-1c9aef9d4ad8.png)

Code Unity:

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Rotate : MonoBehaviour
{
    [SerializeField]
    //Vector3 RotateAmount;
    private float rotSpeed = 5f;

    private UnityMessageManager messanger;
    

    // Start is called before the first frame update
    void Start()
    {
        messanger = new UnityMessageManager();
    }

    private void OnMouseDrag()
    { 
        //Rotate object
        float rotX = Input.GetAxis("Mouse X") * rotSpeed * Mathf.Deg2Rad;
        transform.RotateAround(Vector3.up, -rotX);

        //send message to FLutter
        messanger.SendMessageToFlutter("Test");
    }
}
```
![image](https://user-images.githubusercontent.com/14540114/64381219-f5a9d100-d032-11e9-8f17-79724e0258d9.png)

**Comment by rafbanaan** [comment]
I'm having the same issue here.

**Comment by thomas-stockx** [comment]
Hey guys, sorry for the late reply.

Be sure you use the latest `UnityMessageManager.cs` from the scripts folder.
The issue you're reporting should've been fixed by this PR: https://github.com/snowballdigital/flutter-unity-view-widget/pull/29/
