### ISSUE TITLE
Documentation unclear java module

### ISSUE THREAD

**Issue by Mrgove10** [snowballdigital/flutter-unity-view-widget#45]
Hello,

I do not understand a step in the readme, what is this supposed to mean ?

> After exporting the unity game, open Android Studio and and add the Unity Classes Java .jar file as a module to the unity project. You just need to do this once if you are exporting from the same version of Unity everytime. The .jar file is located in the <Your Flutter Project>/android/UnityExport/lib folder

I do not understand what i am supposed to do here.

Thanks in advance.

**Comment by Elvenisboy** [comment]
> using Unity 2019.2 or older, open build.gradle of UnityExport module and remove these

```   
 bundle {
        language {
            enableSplit = false
        }
        density {
            enableSplit = false
        }
        abi {
            enableSplit = true
        }
    }
```

**Comment by juicycleff** [comment]
@Mrgove10 it's been added to the build script now, thanks to @Elvenisboy :)

**Comment by juicycleff** [comment]
I will be closing this
