### ISSUE TITLE
Objective-C alternative for InitArgs(CommandLine.argc, CommandLine.unsafeArgv)

### ISSUE THREAD

**Issue by TarekMedhat** [snowballdigital/flutter-unity-view-widget#47]
What is the objective-c alternative for those 2 steps ?

3. Add this to your Runner/Runner/Runner-Bridging-Header.h
#import "UnityUtils.h"
Add to AppDelegate.swift before the GeneratePluginRegistrant call:
InitArgs(CommandLine.argc, CommandLine.unsafeArgv)

**Comment by juicycleff** [comment]
@TarekMedhat please clarify your questions. Those are objective-c code

**Comment by TarekMedhat** [comment]
Hi @juicycleff, I'm aware that InitArgs is an Objective-c method and that we are accessing it through Appdelegate.swift by importing it using the bridging header.
But what if my project is in objective-C and the appdelegate is written in objective-c instead of swift (Appdelegate.h & appdelegate.m), how can I call initArg in objective-c and access the commandline argc &argv to pass them as parameters ?
Sorry I've a basic knowledge of ios and Objective-c.
