### ISSUE TITLE
iOS Build Successful but Could Not Load on Device

### ISSUE THREAD

**Issue by gunsym** [snowballdigital/flutter-unity-view-widget#53]
**Environment**

Xcode: 10.3
Target Platform: iOS - 12.0.1 / iPhone 6S (Device)

**Steps to Reproduce**

I had the same problem as in #31 
After receiving error message:
Undefined symbols for architecture arm64:
"_onUnityMessage", referenced from:

Following the steps in #31 , I removed UnityMessageManager.cs, the JsonDotNet folder and link.xml

The build is successful but there is now a 0_abort_with_payload error

This is what I get in the debug log. 
" Referenced from: /var/containers/Bundle/Application/75D04D06-E198-4D91-9B0E-267E82E507BA/Runner.app/Runner  Reason: image not found "

**Actual Behavior**
![Screen Shot 2019-09-26 at 2 48 04 pm](https://user-images.githubusercontent.com/15681540/65660721-e981c400-e072-11e9-8e12-b7d9a314bc9d.png)

Is anybody else having this problem and managed to get around this? Thanks in advance

**Comment by TarekMedhat** [comment]
Make sure that UnityFramework.framwork is added to your Runner > General settings > Embedded Binaries.

**Comment by gunsym** [comment]
Thanks @TarekMedhat , I missed that!

Flutter run works and it launches successfully on the device. 

With Xcode, after including UnityFramework.framework in Embedded Binaries, it fires up on the device. 

Thanks again for the help.

![Screen Shot 2019-09-28 at 9 50 27 pm](https://user-images.githubusercontent.com/15681540/65816023-1b915280-e23a-11e9-8b1e-5fe30548f491.png)

**Comment by TarekMedhat** [comment]
@gunsym You are more than welcome, I'm glad I was able to help :).
