### ISSUE TITLE
cannot find symbol mUnityPlayer.newIntent(intent);

### ISSUE THREAD

**Issue by maine98** [snowballdigital/flutter-unity-view-widget#54]
Hi, i follow your video tutorial but when i build a project, i have this problem:

![error](https://user-images.githubusercontent.com/46499668/66119363-c908bb00-e5d8-11e9-8acf-2eb405ff1df7.PNG)

I state with the saying that I have cloned the master project and replaced the unity project with another one, but it did not give any kind of problem when I executed the export.

**Comment by thomas-stockx** [comment]
If you replaced the Unity project with your own export, make sure to also use the unity-classes.jar from your own exported project.

Unity-classes.jar is exported from Unity as well, and can change based on Unity version. Therefore, if your project was built with a different Unity version, you might have an incompatibel unity-classes.jar file.

**Comment by maine98** [comment]
> If you replaced the Unity project with your own export, make sure to also use the unity-classes.jar from your own exported project.
> 
> Unity-classes.jar is exported from Unity as well, and can change based on Unity version. Therefore, if your project was built with a different Unity version, you might have an incompatibel unity-classes.jar file.

Thank you so much it worked, keep it up!

**Comment by OGmetamonkey** [comment]
> > If you replaced the Unity project with your own export, make sure to also use the unity-classes.jar from your own exported project.
> > Unity-classes.jar is exported from Unity as well, and can change based on Unity version. Therefore, if your project was built with a different Unity version, you might have an incompatibel unity-classes.jar file.
> 
> Thank you so much it worked, keep it up!

So what was your fix?
