### ISSUE TITLE
iOS Flutter Build Build Fail

### ISSUE THREAD

**Issue by sandrush73** [snowballdigital/flutter-unity-view-widget#56]
i have created a build for ios and tried to check initial build but i am getting these errors when i import the UnityMessageManager.cs class in to unity project, anyone here know how to fix this please 

Unity version 2019.3.0a4
Xcode Version 11.0 (11A420a)

`
Showing All Errors Only
Ld /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework normal armv7 (in target 'UnityFramework' from project 'Unity-iPhone')
    cd /Users/arpitasaxena/Downloads/flutter-unity-view-widget-master/ios/UnityExport
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target armv7-apple-ios9.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.0.sdk -L/Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Products/ReleaseForRunning-iphoneos -L/Users/arpitasaxena/Downloads/flutter-unity-view-widget-master/ios/UnityExport/Libraries -F/Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Products/ReleaseForRunning-iphoneos -filelist /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework.LinkFileList -install_name @rpath/UnityFramework.framework/UnityFramework -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -map -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/UnityFramework-LinkMap-normal-armv7.txt -dead_strip -Xlinker -object_path_lto -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_lto.o -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -weak_framework CoreMotion -weak-lSystem -liPhone-lib -framework Security -framework MediaToolbox -framework CoreText -framework AudioToolbox -weak_framework AVFoundation -framework AVKit -framework CFNetwork -framework CoreGraphics -framework CoreMedia -weak_framework CoreMotion -framework CoreVideo -framework Foundation -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -lil2cpp -Xlinker -dependency_info -Xlinker /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/UnityFramework_dependency_info.dat -o /Users/arpitasaxena/Library/Developer/Xcode/DerivedData/Unity-iPhone-hhfffylzhgzeisbnroewaaajtaug/Build/Intermediates.noindex/Unity-iPhone.build/ReleaseForRunning-iphoneos/UnityFramework.build/Objects-normal/armv7/Binary/UnityFramework

Undefined symbols for architecture armv7:
  "_onUnityMessage", referenced from:
      _UnityMessageManager_SendMessageToFlutter_m0ADC2E517A85054AE5BA1D3328255060B20A1570 in Assembly-CSharp.o
      _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4 in Assembly-CSharp.o
     (maybe you meant: _UnityMessageManager_onUnityMessage_mC3031C4585567E720F536DB4EE28B0C20AB8A7C4)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`

**Comment by krunduev** [comment]
I still have the same error

**Comment by LucasTejero** [comment]
For anyone with this issue i fix it doing a downgrade of the ar foundation package to 4.0.0-preview.3 like this:

"com.unity.xr.arcore": "4.0.0-preview.3",
    "com.unity.xr.arfoundation": "4.0.0-preview.3",
    "com.unity.xr.arkit": "4.0.0-preview.3",
    "com.unity.xr.arsubsystems": "4.0.0-preview.3",
