### ISSUE TITLE
Add another .jar file to project

### ISSUE THREAD

**Issue by emadghasempour** [snowballdigital/flutter-unity-view-widget#58]
I have made Unity Project it uses some other jar file itself and It is working in mobile by "Build and Run" in Unity Editor.
Now I am integrating the same project in Flutter so I have exported project to flutter and I have 2 jar files in the exported lib folder (like the image below)
you have created some special folder for flutter-unity-view-widget jar files(unity-classes.jar) and imported it as a project in sample project.
how can I add another jar file to my flutter project?
![img](https://user-images.githubusercontent.com/5299974/66714105-717c0380-edbf-11e9-91fe-09bdafc510cf.jpg)

**Comment by thomas-stockx** [comment]
You can just open the Android project in Android Studio, File -> New Module, select "Import .JAR/.AAR package", and point to your flow.jar file.

That should add your jar to the project.

**Comment by emadghasempour** [comment]
thanks, Thomas I just did so and worked fine
