### ISSUE TITLE
iOS compile fails  Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by sandrush73** [snowballdigital/flutter-unity-view-widget#60]
Hi 
i am trying get a ios build to my iphone, before this i had an error https://github.com/snowballdigital/flutter-unity-view-widget/issues/43 which i fixed by adding `- (void)frameworkWarmup:(int)argc argv:(char*[])argv;` in UnityFramework.h file but i am getting this now 

`Xcode's output:
↳
    === BUILD TARGET flutter_unity_widget OF PROJECT Pods WITH CONFIGURATION Debug ===
    Undefined symbols for architecture arm64:
      "_GetAppController", referenced from:
          -[FUController view] in FlutterUnityWidgetPlugin.o
          ___20-[FUController view]_block_invoke in FlutterUnityWidgetPlugin.o
          +[UnityUtils handleAppStateDidChange:] in UnityUtils.o
          ___27+[UnityUtils createPlayer:]_block_invoke.70 in UnityUtils.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by juicycleff** [comment]
@sandrush73 I have seen this problem and I think it's large to do with the new 
Unity Framework. I am personally looking to fox this this

**Comment by sandrush73** [comment]
@juicycleff Thanks for looking into it.

**Comment by sandrush73** [comment]
is there any workaround with previous unity versions by chance
