### ISSUE TITLE
C# "currentActivity" is null when using inside 'flutter-unity-view-widget'

### ISSUE THREAD

**Issue by emadghasempour** [snowballdigital/flutter-unity-view-widget#65]
I have a unity project in flutter and when I want to get the current activity in unity C# using the code below it just return a null value

this is the code
`AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
 AndroidJavaObject activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");`
and the `activity` object is null
how should I fix this?
_P.S All other third-party libraries in unity that uses this code to get the current activity doesn't work with 'flutter-unity-view-widget'_

**Comment by thomas-stockx** [comment]
Hi Emad,

Can you try "isAR: true"?

This will pass the activity to Unity, but has the side effect of making the
app full screen.

**Comment by emadghasempour** [comment]
Thanks a lot, Thomas. It works. 
but is it possible anyway to run this on normal mode and not fullscreen?

**Comment by thomas-stockx** [comment]
Not at the moment, no. Unity makes some hard coded changes to the activity
it's attached to. Maybe this will change in the future with the work they
are doing on "Unity as a Library", but that's still in beta.
