### ISSUE TITLE
Split up AR and standard examples into separate apps

### ISSUE THREAD

**Issue by thomas-stockx** [snowballdigital/flutter-unity-view-widget#66]
We'll probably need to split up the AR and standard example into two separate apps, as we can't run both examples without code changes anyway.

The current example might be unclear to the end-user, as they might not understand why the example is not fully functional.

**Comment by juicycleff** [comment]
True @thomas-stockx and also it increased the size by a lot.

**Comment by juicycleff** [comment]
I will do that and clean it up
