### ISSUE TITLE
Build iOS, get this:

### ISSUE THREAD

**Issue by playstonex** [snowballdigital/flutter-unity-view-widget#69]
/Users/desi/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+5/ios/Classes/UnityUtils.mm:55:10: error: no visible @interface for
    'UnityFramework' declares the selector 'frameworkWarmup:argv:'
        [ufw frameworkWarmup: g_argc argv: g_argv];
         ~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by nickmeinhold** [comment]
I had the same error, for me it seemed to be caused by the post-build script `XCodePostBuild.cs` not running, as none of the changes were in the exported XCode project.  

I exported the project again - the changes in the post-build script were made this time and no more errors.  Hope that helps.

**Comment by shinriyo** [comment]
you don't exist the error?
```
ios/Classes/FlutterUnityWidgetPlugin.m:12:10: fatal error: 'UnityFramework/UnityFramework.h' file not found
    #include <UnityFramework/UnityFramework.h>
```

**Comment by nickmeinhold** [comment]
Did you do this step in the README?
6. Add UnityFramework.framework as a Library to the Runner project

**Comment by RomanTechnologies** [comment]
As stated by @nickmeinhold, it seems to be an issue with the XCodePostBuild.cs script not running sometimes once the build has completed.

The script is able to run in Unity after the build by declaring above the required method with [PostProcessBuild], which sticks the method into a list of required post build runs, which the script has.

However sometimes it seems it just wont run, even after exporting multiple times in a row.

What worked for me is to specify the run order for the post build by changing it to [PostProcessBuild(0)] informing Unity you want it to be the first thing run straight after the build, before anything else (if anything else)

I am not sure if it will work for everyone, but I am now getting consistent builds without this issue reappearing.

I hope that helps

**Comment by subjectdenied** [comment]
@RomanTechnologies 
had the same issue just now, XCodePostBuild.cs doesn't run sometimes for some reason, that means the unity-sources are not patched, and then stuff is missing

however, this doesnt solve the issue with not being able to build the widget cause "UnityFramework/UnityFramework.h" missing, when trying to do a archive build

**Comment by jbrantl8** [comment]
> What worked for me is to specify the run order for the post build by changing it to [PostProcessBuild(0)] informing Unity you want it to be the first thing run straight after the build, before anything else (if anything else)

Can you give a little more information on how to implement this fix?

**Comment by subjectdenied** [comment]
@jbrantl8 he is talking about Assets/Editor/XCodePostBuild.cs

on around line 44 change:
`
[PostProcessBuild]
`
to this:
`
[PostProcessBuild(0)]
`

**Comment by jbrantl8** [comment]
> @jbrantl8 he is talking about Assets/Editor/XCodePostBuild.cs
> 
> on around line 44 change:
> `[PostProcessBuild]`
> to this:
> `[PostProcessBuild(0)]`

Ok, thanks! Did that, but still getting this error: 

> 'UnityFramework/UnityFramework.h' file not found

I added UnityFramework.framework to Runner like shown in the screenshot here:

<img width="988" alt="Screen Shot 2020-01-23 at 5 34 50 PM" src="https://user-images.githubusercontent.com/16418852/73035812-c25fb700-3e06-11ea-9b46-337965e2cbdc.png">

I also added UnityFramework Target Membership to the Data folder like shown in the screenshot here:

<img width="1271" alt="Screen Shot 2020-01-23 at 5 36 19 PM" src="https://user-images.githubusercontent.com/16418852/73035886-f5a24600-3e06-11ea-99f2-f2c291bde553.png">

The _'UnityFramework/UnityFramework.h' file not found?_  seems to be coming from line 12 of FlutterUnityWidgetPlugin.m located in this directory: 

flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+5/ios/Classes/FlutterUnityWidgetPlugin.m

Help!!

**Comment by subjectdenied** [comment]
@jbrantl8 
see my issue about "building archive for ios" #93 

basically you have to add the unity-iphone project to both the runner and the pods, and then use the unityframework as a dependency for the flutter-unity-widget (inside pods) in its buildphases

**Comment by subjectdenied** [comment]
@jbrantl8 also don't try to build user the flutter cli (i never got this working), only build from xcode

**Comment by subjectdenied** [comment]
<img width="247" alt="Bildschirmfoto 2020-01-24 um 01 52 37" src="https://user-images.githubusercontent.com/8798167/73036641-73d50b80-3e4c-11ea-93d5-941988bf5b8e.png">

**Comment by subjectdenied** [comment]
<img width="989" alt="Bildschirmfoto 2020-01-24 um 01 55 56" src="https://user-images.githubusercontent.com/8798167/73036713-b7c81080-3e4c-11ea-9873-1ca7ffc4d4be.png">

**Comment by subjectdenied** [comment]
<img width="950" alt="Bildschirmfoto 2020-01-24 um 01 57 49" src="https://user-images.githubusercontent.com/8798167/73036792-ffe73300-3e4c-11ea-86c6-c2bcfee65e27.png">

**Comment by jbrantl8** [comment]
Wow, thank you! That solved the framework issue. Now getting 2 more errors when building target Runner.: 
1. 
>  "___gxx_personality_v0", referenced from:
>       UnityFrameworkLoad() in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils handleAppStateDidChange:] in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils listenAppState] in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils createPlayer:] in libflutter_unity_widget.a(UnityUtils.o)
>       ___27+[UnityUtils createPlayer:]_block_invoke.70 in libflutter_unity_widget.a(UnityUtils.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

2. 
> Undefined symbols for architecture armv7:
>   "___gxx_personality_sj0", referenced from:
>       UnityFrameworkLoad() in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils handleAppStateDidChange:] in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils listenAppState] in libflutter_unity_widget.a(UnityUtils.o)
>       +[UnityUtils createPlayer:] in libflutter_unity_widget.a(UnityUtils.o)
>       ___27+[UnityUtils createPlayer:]_block_invoke.70 in libflutter_unity_widget.a(UnityUtils.o)
> ld: symbol(s) not found for architecture armv7
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Looks like it got through almost everything but that...

![Screen Shot 2020-01-23 at 8 00 36 PM](https://user-images.githubusercontent.com/16418852/73041525-183e5a00-3e1b-11ea-9f56-8ba59d7ae055.png)

**Comment by jbrantl8** [comment]
Changing AppDelegate.m to AppDelegate.mm fixes those last errors. I don't fully understand why, other than .mm tells the compiler to recognize both Objective-C and Objective-C++ classes, while .m apparently only does Objective-C classes.

**Comment by jbrantl8** [comment]
Now getting this. What a disaster. 

> 2020-01-24 12:15:13.996383-0700 Runner[4509:888722] Failed to find snapshot: /private/var/containers/Bundle/Application/41D645BC-ED72-40B3-A7CC-318BA5D81EBE/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
> 2020-01-24 12:15:14.090659-0700 Runner[4509:888722] Metal API Validation Enabled
> 2020-01-24 12:15:14.270753-0700 Runner[4509:888919] flutter: Observatory listening on http://127.0.0.1:64207/nW_SGP6iSEY=/
> 2020-01-24 12:15:14.282857-0700 Runner[4509:888907] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
> 2020-01-24 12:15:14.282922-0700 Runner[4509:888907] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.

**Comment by jbrantl8** [comment]
> > 2020-01-24 12:15:13.996383-0700 Runner[4509:888722] Failed to find snapshot: /private/var/containers/Bundle/Application/41D645BC-ED72-40B3-A7CC-318BA5D81EBE/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
> > 2020-01-24 12:15:14.090659-0700 Runner[4509:888722] Metal API Validation Enabled
> > 2020-01-24 12:15:14.270753-0700 Runner[4509:888919] flutter: Observatory listening on http://127.0.0.1:64207/nW_SGP6iSEY=/
> > 2020-01-24 12:15:14.282857-0700 Runner[4509:888907] [VERBOSE-2:engine.cc(127)] Engine run configuration was invalid.
> > 2020-01-24 12:15:14.282922-0700 Runner[4509:888907] [VERBOSE-2:shell.cc(437)] Could not launch engine with configuration.

FYI ~ Rebuilt the project and didn't have this issue again. Not sure what was causing this. If you know, feel free to chime in. It now works! Thanks a ton @subjectdenied

**Comment by MichealReed** [comment]
Finally got things running with the flutter run command. I did several things, but the biggest thanks goes to this:

https://github.com/flutter/flutter/issues/17978#issuecomment-577270917

I also added `s.pod_target_xcconfig = {'VALID_ARCHS' => 'arm64'}'

This will need to be revisited when unity as a library supports the simulator, but should work until then.

**Comment by ideva-SAS** [comment]
Hello
Thanks for this solution, I manage to build the application on my device without any errors.
But when I do a Product / Archive, I get an error:
![image](https://user-images.githubusercontent.com/57949715/75675474-8599a200-5c87-11ea-9a60-e613d750f29e.png)
Could you help me plz ?

Best regards

**Comment by juicycleff** [comment]
Check the updated example. Its a lot easier now to set up on iOS

**Comment by Ahmadre** [comment]
> Check the updated example. Its a lot easier now to set up on iOS

We need more info! Screenshots, paths, better readme, anythimg, but not a single sentence :(

**Comment by uuttff8** [comment]
same problem here, nothing helps
