### ISSUE TITLE
iPhone Export crashes whole device

### ISSUE THREAD

**Issue by Klingens13** [snowballdigital/flutter-unity-view-widget#70]
Hi,

I was trying to add the flutter_unity_plugin using the normal instructions provided in the Readme.md of this repo. _It was throwing out no errors_, as I ran the Xcode Build so I ran it on my iPhone SE. 
But then, not just the app crashed, but the whole Springboard! The phone showed the shut down animation but after 5 seconds it entered the state it's in when it's just booted. (So no Touch ID sign in, etc.) 
When I run it through VSCode or Android Studio the app just crashes after showing the splash screen but the IDE doesn't recognize that it even started. It's just endlessly idling at "Installing and Launching...". It works fine on Android though. 
My Configuration : 
- macOS 10.14.6
- newest versions of the Java JDK (1.8.0_202), Flutter SDK, Dart SDK
- newest versions of Android Studio (3.5.1), VSCode (1.39.2), Xcode (11.1), Unity (2019.3.0b6)
- newest versions of the Flutter Plugins (provided screenshot)

Could someone help me with this?

Thanks for any replies!

More informations provided in attachments:

[Runner  27.10.19, 16-00.crash.txt](https://github.com/snowballdigital/flutter-unity-view-widget/files/3776053/Runner.27.10.19.16-00.crash.txt)
[SpringBoard  27.10.19, 16-00.crash.txt](https://github.com/snowballdigital/flutter-unity-view-widget/files/3776054/SpringBoard.27.10.19.16-00.crash.txt)

![Screenshot 2019-10-27 at 16 08 26](https://user-images.githubusercontent.com/40038209/67637004-98b1f500-f8d6-11e9-87c4-a9f75c617b3b.png)
![Screenshot 2019-10-27 at 16 09 55](https://user-images.githubusercontent.com/40038209/67637005-994a8b80-f8d6-11e9-89b7-c2c89216ac5f.png)

**Comment by thomas-stockx** [comment]
Looks like there might be something wrong with your setup as I see the following in your Springboard log:

```
dependent dylib '@rpath/UnityFramework.framework/UnityFramework' not found for '/private/var/containers/Bundle/Application/17AF5A5C-C725-4C02-B426-91591A8DFEEF/Runner.app/Runner'
```

Could you try going through the steps in the README again?

**Comment by Klingens13** [comment]
Turns out, I had it setup like in the picture in the README :

![Bildschirmfoto 2019-10-28 um 14 42 36](https://user-images.githubusercontent.com/40038209/67683251-57cae680-f991-11e9-97b5-342f4d3fc6af.png)

and not placed in Runner :

![Bildschirmfoto 2019-10-28 um 14 42 45](https://user-images.githubusercontent.com/40038209/67683289-69ac8980-f991-11e9-9965-ca3e1ee8136a.png)
.

But then I also had to fix the *Reason: image not found* error by adding the UnityFramework.framework to the framework list :

![Bildschirmfoto 2019-10-28 um 14 45 20](https://user-images.githubusercontent.com/40038209/67683395-9eb8dc00-f991-11e9-9318-ba772a5fac35.png)

Maybe That should also be included in the README...

@thomas-stockx Thanks for the reply though!

**Comment by krispypen** [comment]
The first step (adding unity-iphone as a child of runner) should not be possible. But adding UnityFramework.framework as a framework in the Runner settings is indeed required. I'll add that to the Readme file!
