### ISSUE TITLE
v0.1.6+5 breaks Xcode compile

### ISSUE THREAD

**Issue by Klingens13** [snowballdigital/flutter-unity-view-widget#73]
Due to the recent changes in the FlutterUnityWidgetPlugin.m file, the line `[GetAppController() setUnityMessageHandler: ^(const char* message)` is breaking the compiling. I needed to fix it by manually download v0.1.6+4 again from the flutter page, because whatever version number I add in the pubspec.yaml file, it forces the v0.1.6+5 version. 
I would appreciate if someone could look into what the problem is, as I have not much experience in Objective C and Swift.
Thanks!

**Comment by krispypen** [comment]
@Klingens13 the XCodePostBuild.cs file was also changed in that release, have you updated it in your unity project and rebuild the project? The Unity-iPhone/Classes/UnityAppController.h should contain this on line 78 after you rebuild it:
``` h
@property (nonatomic, copy)    void(^unityMessageHandler)(const char* message);
```
