### ISSUE TITLE
Unity3d Asset bundles, does it work?

### ISSUE THREAD

**Issue by calvyntwh** [snowballdigital/flutter-unity-view-widget#78]
Does asset bundle still work? Within this widget?

**Comment by juicycleff** [comment]
@calvyntwh all assets are bundled into the app if that's what you mean

**Comment by lorant-csonka-planorama** [comment]
Since unity is running like a native component, you should have no issue with using [AssetBundles](https://docs.unity3d.com/Manual/AssetBundlesIntro.html).

**Comment by calvyntwh** [comment]
Thanks
