### ISSUE TITLE
Issues with building a flutter app using flutter_unity_widget, even after following every step carefully

### ISSUE THREAD

**Issue by lstimac** [snowballdigital/flutter-unity-view-widget#79]
I am trying to run a flutter app using flutter_unity_widget, however even after following all of the steps and checking everything multiple times, I'm still getting the error below. 

Steps I have done:

1.  I added my unity project to "unity" folder stored in android/
2.  Exported Unity project to Android, and placed UnityExport in the android folder
3.  Added unity-classes.jar as module through File -> New -> New module -> path/unity-classes.jar
4. Included  ':unity-classes' and put 

> _include ":UnityExport"
> project(":UnityExport").projectDir = file("./UnityExport")_

in the settings.gradle along with

> dependencies {
>     //implementation fileTree(dir: 'libs', include: ['*.jar'])
>     implementation project(':unity-classes')
> }

in the UnityExport build.gradle

5. Added flutter_unity_widget to pubspec.yaml and done all of the steps listed [here](https://pub.dev/packages/flutter_unity_widget)

### **Error**

>Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve project :UnityExport.
     Required by:
         project :app > project :flutter_unity_widget
      > Unable to find a matching variant of project :UnityExport:

> Could not resolve project :unity-classes.
     Required by:
         project :app > project :flutter_unity_widget
      > Unable to find a matching configuration of project :unity-classes: None of the consumable configurations have attributes.

**Comment by lstimac** [comment]
### Solution

Solved by opening the Unity project located in the 'unity' folder inside app files (it is important to specifically open it from the Flutter app file hierarchy) , and then exporting as Android which will automatically create UnityExport folder in project files. 

Before I figured this out, I used to export Unity project as Android from the original project location and then manually rename the output folder to 'UnityExport', which is ultimately the reason it didn't get recognised during the build.

**Comment by bandaralsehli** [comment]
hello Luka Štimac

pleas can explain how do it ? it can solve with me >>> 

i am waiting for your message

thanks
