### ISSUE TITLE
 Could not find method implementation() for arguments [project ':UnityExport'] 

### ISSUE THREAD

**Issue by CeciMza** [snowballdigital/flutter-unity-view-widget#8]
Hello,

I followed the video (and also double checked everything with the docs), however when I try to build my android project, I am getting this error (sorry if this is not the right place to post this, I am a beginner in both flutter and unity):

Finished with error: Please review your Gradle project setup in the android/ folder.
* Error running Gradle:
ProcessException: Process "/Users/ceciliamzayek/celuna_test/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ceciliamzayek/celuna_test/android/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating root project 'android'.
> Could not find method implementation() for arguments [project ':UnityExport'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/ceciliamzayek/celuna_test/android/gradlew app:properties

**Comment by elPatricko** [comment]
How did you fix this?

**Comment by ceciliamzayek** [comment]
I ended up never needing it because I didn't need Unity for my project anymore
