### ISSUE TITLE
Flutter-unity app on iOS terminates right after the build succeeds

### ISSUE THREAD

**Issue by lstimac** [snowballdigital/flutter-unity-view-widget#81]
I managed to get Android version of Flutter up and running using this widget (including the communication from Unity to Flutter and Flutter to Unity), however I'm having a really hard time doing the same for the iOS version of the app. I tried testing just the basic sample scene with one camera in a scene, and it manages to build after I added

`@property (nonatomic, copy)    void(^unityMessageHandler)(const char* message);`

into the UnityAppController.h on line 78 (I had to add it manually since XCodePostBuild.cs didn't do it based on [#73](https://github.com/snowballdigital/flutter-unity-view-widget/issues/73)). 
However it terminates right after build succeeds with the following error in Xcode:

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UnityAppController setUnityMessageHandler:]

I would extremely appreciate any assistance and suggestions with this issue since I'm a bit stuck with this for the last few days. Full error output can be seen below.

## Error log

> 2019-11-19 23:15:55.924679+0100 Runner[1728:186668] -[UnityAppController setUnityMessageHandler:]: unrecognized selector sent to instance 0x283823780
2019-11-19 23:15:55.926039+0100 Runner[1728:186668] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UnityAppController setUnityMessageHandler:]: unrecognized selector sent to instance 0x283823780'
*** First throw call stack:
(0x18e90427c 0x18dade9f8 0x18e820ab8 0x18e909ac4 0x18e90b75c 0x100bdfb88 0x100f4288c 0x100fbc498 0x100f5c694 0x100fae640 0x100f697b4 0x100f6dce8 0x18e896650 0x18e896380 0x18e895bb4 0x18e890b04 0x18e8900b0 0x190a9079c 0x1baa22978 0x100b4728c 0x18e3558e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

![Screenshot 2019-11-19 at 23 45 58](https://user-images.githubusercontent.com/26429324/69193358-d34e2c80-0b26-11ea-8a0a-068a0b972f1a.png)

**Comment by lstimac** [comment]
I should mention that the app builds and runs successfully if I don't use UnityWidget to load Unity app in flutter. If I use it, error above just pops out and the app terminates while loading the widget. I tried using both versions of XCodePostBuild.cs from this repository but to no avail (I'm not even sure if this occurs because of XCodePostBuild script). Any help would be greatly appreciated :)

**Comment by jbrantl8** [comment]
What version of Unity are you using? I noticed this in the ReadMe: 

> "iOS Platform: 1. This only works with Unity version >=2019.3 because uses Unity as a library! 2. Depending on where you want to test or run your app, (simulator or physical device), you should select the appropriate SDK on Target SDK."

**Comment by TarekMedhat** [comment]
@lstimac Did you find any solutions?

**Comment by juicycleff** [comment]
@TarekMedhat @lstimac The example has been updated and this has been fixed
