### ISSUE TITLE
ios starts Unity in portrait ignoring settings from both Unity and Flutter. 

### ISSUE THREAD

**Issue by Slappiz** [snowballdigital/flutter-unity-view-widget#84]
Ios automatically starts Unity in portrait orientation even though it's locked to Landscape in both Unity and Flutter, this does not happen on android. Anyone have a solution or workaround for this issue?

**Comment by juicycleff** [comment]
Will investigate might be an issue with Unity as a Framework, but I doubt.

**Comment by juicycleff** [comment]
This issue has been resolved. @Slappiz  :)
