### ISSUE TITLE
Select unity scene

### ISSUE THREAD

**Issue by murilinhoPs** [snowballdigital/flutter-unity-view-widget#87]
It's not a issue, I just wanted do know how can I change the current unity scene? Example: my game have 3 scenes, how can I change between them, it must be a method inside unity to change the scene or I can do this inside flutter?

**Comment by PiotrxKolasinski** [comment]
In unity create script with method to load scene. For example:
```
    void openScene(String name)
    {
        SceneManager.LoadScene(name);
    }
```

In flutter call method: postMessage(String gameObject, methodName, message) . For example:
`_unityWidgetController.postMessage('yourGameObjectNameWithScript', "openScene", "sceneNameToOpen")`

**Comment by murilinhoPs** [comment]
Oh, thanks! Now I understood better this .postMessage.
