### ISSUE TITLE
in unity view,can't touch unity

### ISSUE THREAD

**Issue by mrstluo** [snowballdigital/flutter-unity-view-widget#9]
in unity view,can't touch unity

**Comment by juicycleff** [comment]
I will set out time to look into this tomorrow. However, there is a PR from @thomas-stockx that I believe is meant to solve this issue, I will test and make a release now

**Comment by thomas-stockx** [comment]
This should be fixed in master now by #16  👍

**Comment by krispypen** [comment]
Indeed, I can confirm touch input works on both Android and iOS, so this ticket can be closed! 👍

**Comment by juicycleff** [comment]
Yeah tested, this can be closed
