### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by murilinhoPs** [snowballdigital/flutter-unity-view-widget#90]
I don't know why I'm having this problem and I followed all the readme. In my project is everything all right, but in the android/build.gradle from the unity package I always get this error. Can someone help me?

FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/home/murilops/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_unity_widget-0.1.6+5/android/build.gradle' line: 38
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':flutter_unity_widget'.          
> Project with path ':unity-classes' could not be found in project ':flutter_unity_widget'.

**Comment by leemuljadi** [comment]
Have you tried following the video tutorial?

**Comment by murilinhoPs** [comment]
Yes, followed every single step of the tutorial. The only differece, I used a project I already created and not donwloaded the project Demo.

**Comment by leemuljadi** [comment]
Oh yea, I'm having that problem as well. The game worked using the demo project but not with my own project. See this link:
https://github.com/snowballdigital/flutter-unity-view-widget/issues/49

**Comment by murilinhoPs** [comment]
I'll see the link, thanks!

**Comment by leemuljadi** [comment]
No one has ever replied yet.. please let me know you have any update to work it out! thanks!

**Comment by thomas-stockx** [comment]
@murilinhoPs It should work with any Unity project, not just the example.

Can you please share your Flutter project's Android folder structure, and your build.gradle files?

**Comment by subjectdenied** [comment]
make sure you have this at the end of your settings.gradle inside the flutter android folder

`include ":UnityExport"
project(":UnityExport").projectDir = file("./UnityExport")`
