### ISSUE TITLE
Could not determine the dependencies of task ':app:preDebugBuild'

### ISSUE THREAD

**Issue by syah769** [snowballdigital/flutter-unity-view-widget#94]
![prob](https://user-images.githubusercontent.com/37147869/71941390-7bfa3d80-31f4-11ea-8aa0-1cd7b51b7f17.JPG)

I tried to clone from your git and ran in my laptop. But, this is the problem. I'm really frust about this. Help me :(

**Comment by thomas-stockx** [comment]
Exporting the Unity project first is required to run the example, see https://github.com/snowballdigital/flutter-unity-view-widget/blob/master/example/README.md
