### ISSUE TITLE
More than one unity project in flutter app

### ISSUE THREAD

**Issue by syah769** [snowballdigital/flutter-unity-view-widget#96]
I have 2 AR for running in my app. I had tried but one of them must be replace. Anyone had tried to implement two or more AR in app? I'm stuck

**Comment by leemuljadi** [comment]
Hi, have you find a way?

**Comment by syah769** [comment]
> Hi, have you find a way?

**Comment by syah769** [comment]
> Hi, have you find a way?

I switched to the multiple scenes. So, it's easier than multiple project

**Comment by leemuljadi** [comment]
> > Hi, have you find a way?
> 
> I switched to the multiple scenes. So, it's easier than multiple project

Cool! Since actually I am not that familiar with unity, then how do you switch from scene to another scene from flutter?

**Comment by mpfaff** [comment]
@leemuljadi I'm curious about that too. I think you would use the provided `UnityMessageManager`.

**Comment by thomas-stockx** [comment]
@leemuljadi @mpfaff 

You would use the SceneManager.LoadScene method:
https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadScene.html

Just put that in a public method, and follow the steps in regards to "Flutter -> Unity" messaging to trigger that method from Flutter in Unity.

**Comment by Qualcuno** [comment]
I have 2 different project to put inside a flutter app. Merge 2 project to switch between scenes as described above is an hard work. The simple way is switching at runtime between 2 projects. The plugin can do this?

**Comment by mpfaff** [comment]
@Qualcuno the simplest way is **not** to switch between the projects at runtime because that is not supported. If you think it would be simple, why don't you do it yourself? It has been clearly stated that the plugin can **not** do this.

**Comment by kuabhish** [comment]
Hey, every one it's also not clear to me what should be done in the case where you want to run multiple games from the same flutter app. 
Did you guys finally solve it?

**Comment by DivyanshMeta** [comment]
I have to integrate two games in one application, anyone find the answer?

**Comment by omarsalem15** [comment]
how to open 2 different scenes from flutter screen

**Comment by gurpreetkaur1998** [comment]
Can you please share the docs to load different scenes in flutter. I have no idea how to play multiple unity games in flutter using any kind of package. Also, I have tired to play and handle unity project in flutter.

**Comment by MohamedMamdouh-432** [comment]
> > Hi, have you find a way?
> 
> I switched to the multiple scenes. So, it's easier than multiple project

How exactly do you do it ??
