### ISSUE TITLE
Unity to Flutter Messages not coming through

### ISSUE THREAD

**Issue by Klingens13** [snowballdigital/flutter-unity-view-widget#99]
Hey,
I‘m trying to send a message from unity to flutter using the same command as in the default rotate.cs. I‘m also using the same assets as in the example because for some reason my unity export fails with the newer version of that scripts. Also, the ‚Last Changed Date‘ of the unity-classes.jar file is tied to the 07.12.2019 for some reason although all the visible changes in the scene get applied. Can someone please help me with this, because the onUnityMessage() class never gets triggered...

**Comment by leemuljadi** [comment]
Have you followed this:
![image](https://user-images.githubusercontent.com/48749437/73352578-87b5bd00-42e5-11ea-8e06-4b575f43bbcc.png)
And you gotta need to export from unity again if you make any changes to unity files.

**Comment by Klingens13** [comment]
@leemuljadi 
Yes, although I haven't used the exact files from those links because these drop errors for "duplicated packages", I copied these same files over from the example (so from https://github.com/snowballdigital/flutter-unity-view-widget/tree/master/example/unity/DemoApp/Assets ). 
And yes, I've exported the project again.

This is the snippet of the source code.
I can see the "Saved Data to ..." command triggered in the Log.

![image](https://user-images.githubusercontent.com/40038209/73358104-2fa79800-429e-11ea-9395-3ed1bf8068c3.png)


This is not ever triggered, for some reason :

![image](https://user-images.githubusercontent.com/40038209/73358406-d2601680-429e-11ea-975f-f8a94ff51f27.png)

**Comment by Klingens13** [comment]
UPDATE :
I just found out, that the example app I just cloned, and just edited in the way described in the README, (so exported the project again after cloning, etc.) won't trigger the SendMessageToFlutter command either!

![image](https://user-images.githubusercontent.com/40038209/73361785-ee1aeb00-42a5-11ea-8b2b-ed636b296a4a.png)

The only possible reason I could think of, is that something on my unity installation is broke, or is the unity-classes.jar file supposed to always have the "Last Changed Date" of 07.12.2019?

![image](https://user-images.githubusercontent.com/40038209/73361973-49e57400-42a6-11ea-829e-dfc3ea643143.png)

Any responses would be very helpful!

**Comment by leemuljadi** [comment]
Maybe try updating the .jar file as per Tarek Mehdad steps in this link:
https://github.com/snowballdigital/flutter-unity-view-widget/issues/49

**Comment by MichealReed** [comment]
@Klingens13 double check that the UnityMessageManager script is attached a game object in your scene and that you do not have any null reference errors.

**Comment by Klingens13** [comment]
@leemuljadi Yes I had already done that but thanks.
@MichealReed Could you elaborate? If I attach it to a GameObject, for example for me "ModelBase", I get this error...
![image](https://user-images.githubusercontent.com/40038209/73472763-d87ff100-438b-11ea-9e00-b0315cc641ab.png)

**Comment by MichealReed** [comment]
@Klingens13 this error will not block building or the editor's play mode. You can disregard.

**Comment by Klingens13** [comment]
@MichealReed yes, but it still doesn't work...
I mean, the example works, and from there, the UnityMessenger.cs script is also not added to any GameObject... Is there something else I need to set up?

**Comment by Jairolaya12x** [comment]
Add the IEventSystemHandler to the .cs file?

**Comment by Klingens13** [comment]
Apparently, the problem was caused by Flutter. I moved my Unity project in a clean version of the example project and the message went through without any issues... 🤔

**Comment by Klingens13** [comment]
So apparently, my setup is not too far off.
After testing every possible scenario of merging different parts of my project and the example, it turns out that if I just replace all the .dart files with the one main.dart from the example, the messages go through.
I've set up everything in the same way as the example, even checking if the order of the different voids is the same in the dart file, but it still won't work with my application setup.
Could this be fixed by changing the position of the UnityWidget in the widget tree, or is this malfunction may caused by running it inside multiple StatefulWidgets, which are placed in each other?

![Unbenannt3](https://user-images.githubusercontent.com/40038209/74580697-45f46a00-4fa7-11ea-8c76-04e2f9a2ebbe.PNG)
